// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  routes

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( authAccessTokenResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* authAccessTokenResponse ) UnmarshalJSON([]byte) error { return nil }
func ( authAccessTokenResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* authAccessTokenResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_authAccessTokenResponse *authAccessTokenResponse

func ( authMessageResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* authMessageResponse ) UnmarshalJSON([]byte) error { return nil }
func ( authMessageResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* authMessageResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_authMessageResponse *authMessageResponse
