// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package routes

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(in *jlexer.Lexer, out *saveEpisodeProgressRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "position_seconds":
			out.PositionSeconds = int64(in.Int64())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(out *jwriter.Writer, in saveEpisodeProgressRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"position_seconds\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.PositionSeconds))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v saveEpisodeProgressRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v saveEpisodeProgressRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *saveEpisodeProgressRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *saveEpisodeProgressRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(l, v)
}
