// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_VKino/pkg/gen/movie/v1 (interfaces: MovieServiceClient)
//
// Generated by this command:
//
//	mockgen -package=routes -destination=internal/app/api-gateway/routes/movie_client_mock_test.go github.com/go-park-mail-ru/2026_1_VKino/pkg/gen/movie/v1 MovieServiceClient
//

// Package routes is a generated GoMock package.
package routes

import (
	context "context"
	reflect "reflect"

	moviev1 "github.com/go-park-mail-ru/2026_1_VKino/pkg/gen/movie/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockMovieServiceClient is a mock of MovieServiceClient interface.
type MockMovieServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMovieServiceClientMockRecorder
	isgomock struct{}
}

// MockMovieServiceClientMockRecorder is the mock recorder for MockMovieServiceClient.
type MockMovieServiceClientMockRecorder struct {
	mock *MockMovieServiceClient
}

// NewMockMovieServiceClient creates a new mock instance.
func NewMockMovieServiceClient(ctrl *gomock.Controller) *MockMovieServiceClient {
	mock := &MockMovieServiceClient{ctrl: ctrl}
	mock.recorder = &MockMovieServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieServiceClient) EXPECT() *MockMovieServiceClientMockRecorder {
	return m.recorder
}

// GetActorByID mocks base method.
func (m *MockMovieServiceClient) GetActorByID(ctx context.Context, in *moviev1.GetActorByIDRequest, opts ...grpc.CallOption) (*moviev1.GetActorByIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetActorByID", varargs...)
	ret0, _ := ret[0].(*moviev1.GetActorByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorByID indicates an expected call of GetActorByID.
func (mr *MockMovieServiceClientMockRecorder) GetActorByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorByID", reflect.TypeOf((*MockMovieServiceClient)(nil).GetActorByID), varargs...)
}

// GetAllGenres mocks base method.
func (m *MockMovieServiceClient) GetAllGenres(ctx context.Context, in *moviev1.GetAllGenresRequest, opts ...grpc.CallOption) (*moviev1.GetAllGenresResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllGenres", varargs...)
	ret0, _ := ret[0].(*moviev1.GetAllGenresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGenres indicates an expected call of GetAllGenres.
func (mr *MockMovieServiceClientMockRecorder) GetAllGenres(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGenres", reflect.TypeOf((*MockMovieServiceClient)(nil).GetAllGenres), varargs...)
}

// GetAllSelections mocks base method.
func (m *MockMovieServiceClient) GetAllSelections(ctx context.Context, in *moviev1.GetAllSelectionsRequest, opts ...grpc.CallOption) (*moviev1.GetAllSelectionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllSelections", varargs...)
	ret0, _ := ret[0].(*moviev1.GetAllSelectionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSelections indicates an expected call of GetAllSelections.
func (mr *MockMovieServiceClientMockRecorder) GetAllSelections(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSelections", reflect.TypeOf((*MockMovieServiceClient)(nil).GetAllSelections), varargs...)
}

// GetContinueWatching mocks base method.
func (m *MockMovieServiceClient) GetContinueWatching(ctx context.Context, in *moviev1.GetContinueWatchingRequest, opts ...grpc.CallOption) (*moviev1.GetContinueWatchingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetContinueWatching", varargs...)
	ret0, _ := ret[0].(*moviev1.GetContinueWatchingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContinueWatching indicates an expected call of GetContinueWatching.
func (mr *MockMovieServiceClientMockRecorder) GetContinueWatching(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContinueWatching", reflect.TypeOf((*MockMovieServiceClient)(nil).GetContinueWatching), varargs...)
}

// GetEpisodePlayback mocks base method.
func (m *MockMovieServiceClient) GetEpisodePlayback(ctx context.Context, in *moviev1.GetEpisodePlaybackRequest, opts ...grpc.CallOption) (*moviev1.GetEpisodePlaybackResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEpisodePlayback", varargs...)
	ret0, _ := ret[0].(*moviev1.GetEpisodePlaybackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpisodePlayback indicates an expected call of GetEpisodePlayback.
func (mr *MockMovieServiceClientMockRecorder) GetEpisodePlayback(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpisodePlayback", reflect.TypeOf((*MockMovieServiceClient)(nil).GetEpisodePlayback), varargs...)
}

// GetEpisodeProgress mocks base method.
func (m *MockMovieServiceClient) GetEpisodeProgress(ctx context.Context, in *moviev1.GetEpisodeProgressRequest, opts ...grpc.CallOption) (*moviev1.GetEpisodeProgressResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEpisodeProgress", varargs...)
	ret0, _ := ret[0].(*moviev1.GetEpisodeProgressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpisodeProgress indicates an expected call of GetEpisodeProgress.
func (mr *MockMovieServiceClientMockRecorder) GetEpisodeProgress(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpisodeProgress", reflect.TypeOf((*MockMovieServiceClient)(nil).GetEpisodeProgress), varargs...)
}

// GetGenreByID mocks base method.
func (m *MockMovieServiceClient) GetGenreByID(ctx context.Context, in *moviev1.GetGenreByIDRequest, opts ...grpc.CallOption) (*moviev1.GetGenreByIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGenreByID", varargs...)
	ret0, _ := ret[0].(*moviev1.GetGenreByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenreByID indicates an expected call of GetGenreByID.
func (mr *MockMovieServiceClientMockRecorder) GetGenreByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenreByID", reflect.TypeOf((*MockMovieServiceClient)(nil).GetGenreByID), varargs...)
}

// GetMovieByID mocks base method.
func (m *MockMovieServiceClient) GetMovieByID(ctx context.Context, in *moviev1.GetMovieByIDRequest, opts ...grpc.CallOption) (*moviev1.GetMovieByIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMovieByID", varargs...)
	ret0, _ := ret[0].(*moviev1.GetMovieByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovieByID indicates an expected call of GetMovieByID.
func (mr *MockMovieServiceClientMockRecorder) GetMovieByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovieByID", reflect.TypeOf((*MockMovieServiceClient)(nil).GetMovieByID), varargs...)
}

// GetMoviesByIDs mocks base method.
func (m *MockMovieServiceClient) GetMoviesByIDs(ctx context.Context, in *moviev1.GetMoviesByIDsRequest, opts ...grpc.CallOption) (*moviev1.GetMoviesByIDsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMoviesByIDs", varargs...)
	ret0, _ := ret[0].(*moviev1.GetMoviesByIDsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMoviesByIDs indicates an expected call of GetMoviesByIDs.
func (mr *MockMovieServiceClientMockRecorder) GetMoviesByIDs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoviesByIDs", reflect.TypeOf((*MockMovieServiceClient)(nil).GetMoviesByIDs), varargs...)
}

// GetSelectionByTitle mocks base method.
func (m *MockMovieServiceClient) GetSelectionByTitle(ctx context.Context, in *moviev1.GetSelectionByTitleRequest, opts ...grpc.CallOption) (*moviev1.GetSelectionByTitleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSelectionByTitle", varargs...)
	ret0, _ := ret[0].(*moviev1.GetSelectionByTitleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectionByTitle indicates an expected call of GetSelectionByTitle.
func (mr *MockMovieServiceClientMockRecorder) GetSelectionByTitle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectionByTitle", reflect.TypeOf((*MockMovieServiceClient)(nil).GetSelectionByTitle), varargs...)
}

// GetWatchHistory mocks base method.
func (m *MockMovieServiceClient) GetWatchHistory(ctx context.Context, in *moviev1.GetWatchHistoryRequest, opts ...grpc.CallOption) (*moviev1.GetWatchHistoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWatchHistory", varargs...)
	ret0, _ := ret[0].(*moviev1.GetWatchHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatchHistory indicates an expected call of GetWatchHistory.
func (mr *MockMovieServiceClientMockRecorder) GetWatchHistory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchHistory", reflect.TypeOf((*MockMovieServiceClient)(nil).GetWatchHistory), varargs...)
}

// SaveEpisodeProgress mocks base method.
func (m *MockMovieServiceClient) SaveEpisodeProgress(ctx context.Context, in *moviev1.SaveEpisodeProgressRequest, opts ...grpc.CallOption) (*moviev1.SaveEpisodeProgressResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveEpisodeProgress", varargs...)
	ret0, _ := ret[0].(*moviev1.SaveEpisodeProgressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveEpisodeProgress indicates an expected call of SaveEpisodeProgress.
func (mr *MockMovieServiceClientMockRecorder) SaveEpisodeProgress(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEpisodeProgress", reflect.TypeOf((*MockMovieServiceClient)(nil).SaveEpisodeProgress), varargs...)
}

// SearchMovies mocks base method.
func (m *MockMovieServiceClient) SearchMovies(ctx context.Context, in *moviev1.SearchMoviesRequest, opts ...grpc.CallOption) (*moviev1.SearchMoviesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchMovies", varargs...)
	ret0, _ := ret[0].(*moviev1.SearchMoviesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMovies indicates an expected call of SearchMovies.
func (mr *MockMovieServiceClientMockRecorder) SearchMovies(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMovies", reflect.TypeOf((*MockMovieServiceClient)(nil).SearchMovies), varargs...)
}
