// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package routes

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(in *jlexer.Lexer, out *partyVoteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "option_id":
			out.OptionID = int64(in.Int64())
		case "coins_amount":
			out.CoinsAmount = int32(in.Int32())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(out *jwriter.Writer, in partyVoteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"option_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.OptionID))
	}
	{
		const prefix string = ",\"coins_amount\":"
		out.RawString(prefix)
		out.Int32(int32(in.CoinsAmount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v partyVoteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v partyVoteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *partyVoteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *partyVoteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(l, v)
}
func easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(in *jlexer.Lexer, out *partyResolvePollRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "option_id":
			out.OptionID = int64(in.Int64())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(out *jwriter.Writer, in partyResolvePollRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"option_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.OptionID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v partyResolvePollRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v partyResolvePollRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *partyResolvePollRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *partyResolvePollRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(l, v)
}
func easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(in *jlexer.Lexer, out *partyPollRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "question":
			out.Question = string(in.String())
		case "options":
			if in.IsNull() {
				in.Skip()
				out.Options = nil
			} else {
				in.Delim('[')
				if out.Options == nil {
					if !in.IsDelim(']') {
						out.Options = make([]string, 0, 4)
					} else {
						out.Options = []string{}
					}
				} else {
					out.Options = (out.Options)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Options = append(out.Options, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(out *jwriter.Writer, in partyPollRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"question\":"
		out.RawString(prefix[1:])
		out.String(string(in.Question))
	}
	{
		const prefix string = ",\"options\":"
		out.RawString(prefix)
		if in.Options == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Options {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v partyPollRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v partyPollRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *partyPollRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *partyPollRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(l, v)
}
func easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(in *jlexer.Lexer, out *partyMessageRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "content":
			out.Content = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(out *jwriter.Writer, in partyMessageRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix[1:])
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v partyMessageRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v partyMessageRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *partyMessageRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *partyMessageRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(l, v)
}
func easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(in *jlexer.Lexer, out *partyActionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "action":
			out.Action = string(in.String())
		case "movie_id":
			out.MovieID = int64(in.Int64())
		case "episode_id":
			out.EpisodeID = int64(in.Int64())
		case "playback_url":
			out.PlaybackURL = string(in.String())
		case "duration_seconds":
			out.DurationSeconds = int64(in.Int64())
		case "position_seconds":
			out.PositionSeconds = int64(in.Int64())
		case "status":
			out.Status = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(out *jwriter.Writer, in partyActionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"action\":"
		out.RawString(prefix[1:])
		out.String(string(in.Action))
	}
	{
		const prefix string = ",\"movie_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.MovieID))
	}
	{
		const prefix string = ",\"episode_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.EpisodeID))
	}
	{
		const prefix string = ",\"playback_url\":"
		out.RawString(prefix)
		out.String(string(in.PlaybackURL))
	}
	{
		const prefix string = ",\"duration_seconds\":"
		out.RawString(prefix)
		out.Int64(int64(in.DurationSeconds))
	}
	{
		const prefix string = ",\"position_seconds\":"
		out.RawString(prefix)
		out.Int64(int64(in.PositionSeconds))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v partyActionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v partyActionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *partyActionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *partyActionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(l, v)
}
func easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(in *jlexer.Lexer, out *joinPartyRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "invite_link":
			out.InviteLink = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(out *jwriter.Writer, in joinPartyRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"invite_link\":"
		out.RawString(prefix[1:])
		out.String(string(in.InviteLink))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v joinPartyRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v joinPartyRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *joinPartyRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *joinPartyRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(l, v)
}
func easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(in *jlexer.Lexer, out *inviteFriendToPartyRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "room_id":
			out.RoomID = int64(in.Int64())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(out *jwriter.Writer, in inviteFriendToPartyRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"room_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.RoomID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v inviteFriendToPartyRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v inviteFriendToPartyRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *inviteFriendToPartyRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *inviteFriendToPartyRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(l, v)
}
func easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes7(in *jlexer.Lexer, out *createPartyRoomRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "visibility":
			out.Visibility = string(in.String())
		case "movie_id":
			out.MovieID = int64(in.Int64())
		case "episode_id":
			out.EpisodeID = int64(in.Int64())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes7(out *jwriter.Writer, in createPartyRoomRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"visibility\":"
		out.RawString(prefix)
		out.String(string(in.Visibility))
	}
	{
		const prefix string = ",\"movie_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.MovieID))
	}
	{
		const prefix string = ",\"episode_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.EpisodeID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createPartyRoomRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createPartyRoomRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2271fc62EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createPartyRoomRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createPartyRoomRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2271fc62DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes7(l, v)
}
