// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package routes

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(in *jlexer.Lexer, out *moneyTariffResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "code":
			out.Code = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "price_money":
			out.PriceMoney = int32(in.Int32())
		case "price_vkino_coins":
			out.PriceVkinoCoins = int32(in.Int32())
		case "is_money_payment_available":
			out.IsMoneyPaymentAvailable = bool(in.Bool())
		case "is_coins_payment_available":
			out.IsCoinsPaymentAvailable = bool(in.Bool())
		case "duration_days":
			out.DurationDays = int32(in.Int32())
		case "level":
			out.Level = int32(in.Int32())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(out *jwriter.Writer, in moneyTariffResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"price_money\":"
		out.RawString(prefix)
		out.Int32(int32(in.PriceMoney))
	}
	{
		const prefix string = ",\"price_vkino_coins\":"
		out.RawString(prefix)
		out.Int32(int32(in.PriceVkinoCoins))
	}
	{
		const prefix string = ",\"is_money_payment_available\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsMoneyPaymentAvailable))
	}
	{
		const prefix string = ",\"is_coins_payment_available\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsCoinsPaymentAvailable))
	}
	{
		const prefix string = ",\"duration_days\":"
		out.RawString(prefix)
		out.Int32(int32(in.DurationDays))
	}
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		out.Int32(int32(in.Level))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v moneyTariffResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v moneyTariffResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *moneyTariffResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *moneyTariffResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(l, v)
}
func easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(in *jlexer.Lexer, out *listMoneyTariffsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tariffs":
			if in.IsNull() {
				in.Skip()
				out.Tariffs = nil
			} else {
				in.Delim('[')
				if out.Tariffs == nil {
					if !in.IsDelim(']') {
						out.Tariffs = make([]moneyTariffResponse, 0, 1)
					} else {
						out.Tariffs = []moneyTariffResponse{}
					}
				} else {
					out.Tariffs = (out.Tariffs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 moneyTariffResponse
					(v1).UnmarshalEasyJSON(in)
					out.Tariffs = append(out.Tariffs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(out *jwriter.Writer, in listMoneyTariffsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tariffs\":"
		out.RawString(prefix[1:])
		if in.Tariffs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Tariffs {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v listMoneyTariffsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v listMoneyTariffsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *listMoneyTariffsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *listMoneyTariffsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(l, v)
}
func easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(in *jlexer.Lexer, out *listCoinsPacksResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "packs":
			if in.IsNull() {
				in.Skip()
				out.Packs = nil
			} else {
				in.Delim('[')
				if out.Packs == nil {
					if !in.IsDelim(']') {
						out.Packs = make([]coinsPackResponse, 0, 2)
					} else {
						out.Packs = []coinsPackResponse{}
					}
				} else {
					out.Packs = (out.Packs)[:0]
				}
				for !in.IsDelim(']') {
					var v4 coinsPackResponse
					(v4).UnmarshalEasyJSON(in)
					out.Packs = append(out.Packs, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(out *jwriter.Writer, in listCoinsPacksResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"packs\":"
		out.RawString(prefix[1:])
		if in.Packs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Packs {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v listCoinsPacksResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v listCoinsPacksResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *listCoinsPacksResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *listCoinsPacksResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(l, v)
}
func easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(in *jlexer.Lexer, out *getPaymentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "payment_id":
			out.PaymentID = int64(in.Int64())
		case "product_type":
			out.ProductType = string(in.String())
		case "product_ref_id":
			out.ProductRefID = int64(in.Int64())
		case "status":
			out.Status = string(in.String())
		case "amount":
			out.Amount = string(in.String())
		case "currency":
			out.Currency = string(in.String())
		case "payment_method":
			out.PaymentMethod = string(in.String())
		case "confirmation_url":
			if in.IsNull() {
				in.Skip()
				out.ConfirmationURL = nil
			} else {
				if out.ConfirmationURL == nil {
					out.ConfirmationURL = new(string)
				}
				*out.ConfirmationURL = string(in.String())
			}
		case "paid_at":
			if in.IsNull() {
				in.Skip()
				out.PaidAt = nil
			} else {
				if out.PaidAt == nil {
					out.PaidAt = new(string)
				}
				*out.PaidAt = string(in.String())
			}
		case "coins_spent":
			if in.IsNull() {
				in.Skip()
				out.CoinsSpent = nil
			} else {
				if out.CoinsSpent == nil {
					out.CoinsSpent = new(int32)
				}
				*out.CoinsSpent = int32(in.Int32())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(out *jwriter.Writer, in getPaymentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"payment_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.PaymentID))
	}
	{
		const prefix string = ",\"product_type\":"
		out.RawString(prefix)
		out.String(string(in.ProductType))
	}
	{
		const prefix string = ",\"product_ref_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ProductRefID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"currency\":"
		out.RawString(prefix)
		out.String(string(in.Currency))
	}
	{
		const prefix string = ",\"payment_method\":"
		out.RawString(prefix)
		out.String(string(in.PaymentMethod))
	}
	if in.ConfirmationURL != nil {
		const prefix string = ",\"confirmation_url\":"
		out.RawString(prefix)
		out.String(string(*in.ConfirmationURL))
	}
	if in.PaidAt != nil {
		const prefix string = ",\"paid_at\":"
		out.RawString(prefix)
		out.String(string(*in.PaidAt))
	}
	if in.CoinsSpent != nil {
		const prefix string = ",\"coins_spent\":"
		out.RawString(prefix)
		out.Int32(int32(*in.CoinsSpent))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getPaymentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getPaymentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getPaymentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getPaymentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(l, v)
}
func easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(in *jlexer.Lexer, out *createPaymentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "payment_id":
			out.PaymentID = int64(in.Int64())
		case "status":
			out.Status = string(in.String())
		case "confirmation_url":
			out.ConfirmationURL = string(in.String())
		case "payment_method":
			out.PaymentMethod = string(in.String())
		case "coins_spent":
			if in.IsNull() {
				in.Skip()
				out.CoinsSpent = nil
			} else {
				if out.CoinsSpent == nil {
					out.CoinsSpent = new(int32)
				}
				*out.CoinsSpent = int32(in.Int32())
			}
		case "vkino_coins_balance":
			if in.IsNull() {
				in.Skip()
				out.VkinoCoinsBalance = nil
			} else {
				if out.VkinoCoinsBalance == nil {
					out.VkinoCoinsBalance = new(int32)
				}
				*out.VkinoCoinsBalance = int32(in.Int32())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(out *jwriter.Writer, in createPaymentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"payment_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.PaymentID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"confirmation_url\":"
		out.RawString(prefix)
		out.String(string(in.ConfirmationURL))
	}
	{
		const prefix string = ",\"payment_method\":"
		out.RawString(prefix)
		out.String(string(in.PaymentMethod))
	}
	if in.CoinsSpent != nil {
		const prefix string = ",\"coins_spent\":"
		out.RawString(prefix)
		out.Int32(int32(*in.CoinsSpent))
	}
	if in.VkinoCoinsBalance != nil {
		const prefix string = ",\"vkino_coins_balance\":"
		out.RawString(prefix)
		out.Int32(int32(*in.VkinoCoinsBalance))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createPaymentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createPaymentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createPaymentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createPaymentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes4(l, v)
}
func easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(in *jlexer.Lexer, out *createPaymentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "product_type":
			out.ProductType = string(in.String())
		case "product_ref_id":
			out.ProductRefID = int64(in.Int64())
		case "payment_method":
			out.PaymentMethod = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(out *jwriter.Writer, in createPaymentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"product_type\":"
		out.RawString(prefix[1:])
		out.String(string(in.ProductType))
	}
	{
		const prefix string = ",\"product_ref_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ProductRefID))
	}
	if in.PaymentMethod != "" {
		const prefix string = ",\"payment_method\":"
		out.RawString(prefix)
		out.String(string(in.PaymentMethod))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createPaymentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createPaymentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createPaymentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createPaymentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes5(l, v)
}
func easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(in *jlexer.Lexer, out *coinsPackResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "title":
			out.Title = string(in.String())
		case "coins_amount":
			out.CoinsAmount = int32(in.Int32())
		case "price_money":
			out.PriceMoney = int32(in.Int32())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(out *jwriter.Writer, in coinsPackResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"coins_amount\":"
		out.RawString(prefix)
		out.Int32(int32(in.CoinsAmount))
	}
	{
		const prefix string = ",\"price_money\":"
		out.RawString(prefix)
		out.Int32(int32(in.PriceMoney))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v coinsPackResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v coinsPackResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *coinsPackResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *coinsPackResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes6(l, v)
}
