// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_VKino/pkg/gen/payment/v1 (interfaces: PaymentServiceClient)
//
// Generated by this command:
//
//	mockgen -package=routes -destination=internal/app/api-gateway/routes/payment_client_mock_test.go github.com/go-park-mail-ru/2026_1_VKino/pkg/gen/payment/v1 PaymentServiceClient
//

// Package routes is a generated GoMock package.
package routes

import (
	context "context"
	reflect "reflect"

	paymentv1 "github.com/go-park-mail-ru/2026_1_VKino/pkg/gen/payment/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPaymentServiceClient is a mock of PaymentServiceClient interface.
type MockPaymentServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceClientMockRecorder
	isgomock struct{}
}

// MockPaymentServiceClientMockRecorder is the mock recorder for MockPaymentServiceClient.
type MockPaymentServiceClientMockRecorder struct {
	mock *MockPaymentServiceClient
}

// NewMockPaymentServiceClient creates a new mock instance.
func NewMockPaymentServiceClient(ctrl *gomock.Controller) *MockPaymentServiceClient {
	mock := &MockPaymentServiceClient{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentServiceClient) EXPECT() *MockPaymentServiceClientMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentServiceClient) CreatePayment(ctx context.Context, in *paymentv1.CreatePaymentRequest, opts ...grpc.CallOption) (*paymentv1.CreatePaymentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreatePayment", varargs...)
	ret0, _ := ret[0].(*paymentv1.CreatePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentServiceClientMockRecorder) CreatePayment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentServiceClient)(nil).CreatePayment), varargs...)
}

// GetPayment mocks base method.
func (m *MockPaymentServiceClient) GetPayment(ctx context.Context, in *paymentv1.GetPaymentRequest, opts ...grpc.CallOption) (*paymentv1.GetPaymentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPayment", varargs...)
	ret0, _ := ret[0].(*paymentv1.GetPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockPaymentServiceClientMockRecorder) GetPayment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockPaymentServiceClient)(nil).GetPayment), varargs...)
}

// HandleYooKassaWebhook mocks base method.
func (m *MockPaymentServiceClient) HandleYooKassaWebhook(ctx context.Context, in *paymentv1.HandleYooKassaWebhookRequest, opts ...grpc.CallOption) (*paymentv1.HandleYooKassaWebhookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HandleYooKassaWebhook", varargs...)
	ret0, _ := ret[0].(*paymentv1.HandleYooKassaWebhookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleYooKassaWebhook indicates an expected call of HandleYooKassaWebhook.
func (mr *MockPaymentServiceClientMockRecorder) HandleYooKassaWebhook(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleYooKassaWebhook", reflect.TypeOf((*MockPaymentServiceClient)(nil).HandleYooKassaWebhook), varargs...)
}

// ListMoneyTariffs mocks base method.
func (m *MockPaymentServiceClient) ListMoneyTariffs(ctx context.Context, in *paymentv1.ListMoneyTariffsRequest, opts ...grpc.CallOption) (*paymentv1.ListMoneyTariffsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMoneyTariffs", varargs...)
	ret0, _ := ret[0].(*paymentv1.ListMoneyTariffsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMoneyTariffs indicates an expected call of ListMoneyTariffs.
func (mr *MockPaymentServiceClientMockRecorder) ListMoneyTariffs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMoneyTariffs", reflect.TypeOf((*MockPaymentServiceClient)(nil).ListMoneyTariffs), varargs...)
}
