// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package routes

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFfbd3743DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(in *jlexer.Lexer, out *subscriptionHTTPErrorResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "error":
			(out.Error).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFfbd3743EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(out *jwriter.Writer, in subscriptionHTTPErrorResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		(in.Error).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v subscriptionHTTPErrorResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFfbd3743EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v subscriptionHTTPErrorResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFfbd3743EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *subscriptionHTTPErrorResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFfbd3743DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *subscriptionHTTPErrorResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFfbd3743DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(l, v)
}
func easyjsonFfbd3743DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(in *jlexer.Lexer, out *subscriptionHTTPError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = string(in.String())
		case "feature":
			out.Feature = string(in.String())
		case "message":
			out.Message = string(in.String())
		case "current_level":
			if in.IsNull() {
				in.Skip()
				out.CurrentLevel = nil
			} else {
				if out.CurrentLevel == nil {
					out.CurrentLevel = new(int32)
				}
				*out.CurrentLevel = int32(in.Int32())
			}
		case "required_level":
			if in.IsNull() {
				in.Skip()
				out.RequiredLevel = nil
			} else {
				if out.RequiredLevel == nil {
					out.RequiredLevel = new(int32)
				}
				*out.RequiredLevel = int32(in.Int32())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
				out.Limit = nil
			} else {
				if out.Limit == nil {
					out.Limit = new(int32)
				}
				*out.Limit = int32(in.Int32())
			}
		case "used":
			if in.IsNull() {
				in.Skip()
				out.Used = nil
			} else {
				if out.Used == nil {
					out.Used = new(int32)
				}
				*out.Used = int32(in.Int32())
			}
		case "remaining":
			if in.IsNull() {
				in.Skip()
				out.Remaining = nil
			} else {
				if out.Remaining == nil {
					out.Remaining = new(int32)
				}
				*out.Remaining = int32(in.Int32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFfbd3743EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(out *jwriter.Writer, in subscriptionHTTPError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"feature\":"
		out.RawString(prefix)
		out.String(string(in.Feature))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	if in.CurrentLevel != nil {
		const prefix string = ",\"current_level\":"
		out.RawString(prefix)
		out.Int32(int32(*in.CurrentLevel))
	}
	if in.RequiredLevel != nil {
		const prefix string = ",\"required_level\":"
		out.RawString(prefix)
		out.Int32(int32(*in.RequiredLevel))
	}
	if in.Limit != nil {
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int32(int32(*in.Limit))
	}
	if in.Used != nil {
		const prefix string = ",\"used\":"
		out.RawString(prefix)
		out.Int32(int32(*in.Used))
	}
	if in.Remaining != nil {
		const prefix string = ",\"remaining\":"
		out.RawString(prefix)
		out.Int32(int32(*in.Remaining))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v subscriptionHTTPError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFfbd3743EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v subscriptionHTTPError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFfbd3743EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *subscriptionHTTPError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFfbd3743DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *subscriptionHTTPError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFfbd3743DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(l, v)
}
