// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package routes

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(in *jlexer.Lexer, out *subscriptionUsageResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "coins_received_today":
			out.CoinsReceivedToday = int32(in.Int32())
		case "coins_remaining_today":
			out.CoinsRemainingToday = int32(in.Int32())
		case "rooms_created_this_month":
			out.RoomsCreatedThisMonth = int32(in.Int32())
		case "rooms_remaining_this_month":
			if in.IsNull() {
				in.Skip()
				out.RoomsRemainingThisMonth = nil
			} else {
				if out.RoomsRemainingThisMonth == nil {
					out.RoomsRemainingThisMonth = new(int32)
				}
				*out.RoomsRemainingThisMonth = int32(in.Int32())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(out *jwriter.Writer, in subscriptionUsageResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coins_received_today\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.CoinsReceivedToday))
	}
	{
		const prefix string = ",\"coins_remaining_today\":"
		out.RawString(prefix)
		out.Int32(int32(in.CoinsRemainingToday))
	}
	{
		const prefix string = ",\"rooms_created_this_month\":"
		out.RawString(prefix)
		out.Int32(int32(in.RoomsCreatedThisMonth))
	}
	{
		const prefix string = ",\"rooms_remaining_this_month\":"
		out.RawString(prefix)
		if in.RoomsRemainingThisMonth == nil {
			out.RawString("null")
		} else {
			out.Int32(int32(*in.RoomsRemainingThisMonth))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v subscriptionUsageResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v subscriptionUsageResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *subscriptionUsageResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *subscriptionUsageResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes(l, v)
}
func easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(in *jlexer.Lexer, out *subscriptionStateResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "subscription":
			(out.Subscription).UnmarshalEasyJSON(in)
		case "capabilities":
			(out.Capabilities).UnmarshalEasyJSON(in)
		case "usage":
			(out.Usage).UnmarshalEasyJSON(in)
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(out *jwriter.Writer, in subscriptionStateResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subscription\":"
		out.RawString(prefix[1:])
		(in.Subscription).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"capabilities\":"
		out.RawString(prefix)
		(in.Capabilities).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"usage\":"
		out.RawString(prefix)
		(in.Usage).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v subscriptionStateResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v subscriptionStateResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *subscriptionStateResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *subscriptionStateResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes1(l, v)
}
func easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(in *jlexer.Lexer, out *subscriptionInfoResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "code":
			out.Code = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "level":
			out.Level = int32(in.Int32())
		case "active_until":
			if in.IsNull() {
				in.Skip()
				out.ActiveUntil = nil
			} else {
				if out.ActiveUntil == nil {
					out.ActiveUntil = new(string)
				}
				*out.ActiveUntil = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(out *jwriter.Writer, in subscriptionInfoResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		out.Int32(int32(in.Level))
	}
	if in.ActiveUntil != nil {
		const prefix string = ",\"active_until\":"
		out.RawString(prefix)
		out.String(string(*in.ActiveUntil))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v subscriptionInfoResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v subscriptionInfoResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *subscriptionInfoResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *subscriptionInfoResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes2(l, v)
}
func easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(in *jlexer.Lexer, out *subscriptionCapabilitiesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "can_watch_paid_content":
			out.CanWatchPaidContent = bool(in.Bool())
		case "can_use_smart_continue":
			out.CanUseSmartContinue = bool(in.Bool())
		case "ad_policy":
			out.AdPolicy = string(in.String())
		case "daily_coins_limit":
			out.DailyCoinsLimit = int32(in.Int32())
		case "monthly_room_limit":
			if in.IsNull() {
				in.Skip()
				out.MonthlyRoomLimit = nil
			} else {
				if out.MonthlyRoomLimit == nil {
					out.MonthlyRoomLimit = new(int32)
				}
				*out.MonthlyRoomLimit = int32(in.Int32())
			}
		case "max_room_members":
			out.MaxRoomMembers = int32(in.Int32())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(out *jwriter.Writer, in subscriptionCapabilitiesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"can_watch_paid_content\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.CanWatchPaidContent))
	}
	{
		const prefix string = ",\"can_use_smart_continue\":"
		out.RawString(prefix)
		out.Bool(bool(in.CanUseSmartContinue))
	}
	{
		const prefix string = ",\"ad_policy\":"
		out.RawString(prefix)
		out.String(string(in.AdPolicy))
	}
	{
		const prefix string = ",\"daily_coins_limit\":"
		out.RawString(prefix)
		out.Int32(int32(in.DailyCoinsLimit))
	}
	{
		const prefix string = ",\"monthly_room_limit\":"
		out.RawString(prefix)
		if in.MonthlyRoomLimit == nil {
			out.RawString("null")
		} else {
			out.Int32(int32(*in.MonthlyRoomLimit))
		}
	}
	{
		const prefix string = ",\"max_room_members\":"
		out.RawString(prefix)
		out.Int32(int32(in.MaxRoomMembers))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v subscriptionCapabilitiesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v subscriptionCapabilitiesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9f60fe09EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *subscriptionCapabilitiesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *subscriptionCapabilitiesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9f60fe09DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayRoutes3(l, v)
}
