// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/api-gateway/routes/user.go
//
// Generated by this command:
//
//	mockgen -package=routes -source=internal/app/api-gateway/routes/user.go -destination=internal/app/api-gateway/routes/user_client_mock_test.go UserClient
//

// Package routes is a generated GoMock package.
package routes

import (
	context "context"
	reflect "reflect"

	moviev1 "github.com/go-park-mail-ru/2026_1_VKino/pkg/gen/movie/v1"
	supportv1 "github.com/go-park-mail-ru/2026_1_VKino/pkg/gen/support/v1"
	userv1 "github.com/go-park-mail-ru/2026_1_VKino/pkg/gen/user/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockUserClient is a mock of UserClient interface.
type MockUserClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserClientMockRecorder
	isgomock struct{}
}

// MockUserClientMockRecorder is the mock recorder for MockUserClient.
type MockUserClientMockRecorder struct {
	mock *MockUserClient
}

// NewMockUserClient creates a new mock instance.
func NewMockUserClient(ctrl *gomock.Controller) *MockUserClient {
	mock := &MockUserClient{ctrl: ctrl}
	mock.recorder = &MockUserClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserClient) EXPECT() *MockUserClientMockRecorder {
	return m.recorder
}

// AddFriend mocks base method.
func (m *MockUserClient) AddFriend(ctx context.Context, in *userv1.AddFriendRequest, opts ...grpc.CallOption) (*userv1.AddFriendResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddFriend", varargs...)
	ret0, _ := ret[0].(*userv1.AddFriendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFriend indicates an expected call of AddFriend.
func (mr *MockUserClientMockRecorder) AddFriend(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFriend", reflect.TypeOf((*MockUserClient)(nil).AddFriend), varargs...)
}

// AddMovieToFavorites mocks base method.
func (m *MockUserClient) AddMovieToFavorites(ctx context.Context, in *userv1.AddMovieToFavoritesRequest, opts ...grpc.CallOption) (*userv1.AddMovieToFavoritesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddMovieToFavorites", varargs...)
	ret0, _ := ret[0].(*userv1.AddMovieToFavoritesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMovieToFavorites indicates an expected call of AddMovieToFavorites.
func (mr *MockUserClientMockRecorder) AddMovieToFavorites(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMovieToFavorites", reflect.TypeOf((*MockUserClient)(nil).AddMovieToFavorites), varargs...)
}

// CreateTicket mocks base method.
func (m *MockUserClient) CreateTicket(ctx context.Context, in *supportv1.CreateTicketRequest, opts ...grpc.CallOption) (*supportv1.TicketResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTicket", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicket indicates an expected call of CreateTicket.
func (mr *MockUserClientMockRecorder) CreateTicket(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicket", reflect.TypeOf((*MockUserClient)(nil).CreateTicket), varargs...)
}

// CreateTicketMessage mocks base method.
func (m *MockUserClient) CreateTicketMessage(ctx context.Context, in *supportv1.CreateTicketMessageRequest, opts ...grpc.CallOption) (*supportv1.TicketMessageResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTicketMessage", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicketMessage indicates an expected call of CreateTicketMessage.
func (mr *MockUserClientMockRecorder) CreateTicketMessage(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicketMessage", reflect.TypeOf((*MockUserClient)(nil).CreateTicketMessage), varargs...)
}

// DeleteFriend mocks base method.
func (m *MockUserClient) DeleteFriend(ctx context.Context, in *userv1.DeleteFriendRequest, opts ...grpc.CallOption) (*userv1.DeleteFriendResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFriend", varargs...)
	ret0, _ := ret[0].(*userv1.DeleteFriendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFriend indicates an expected call of DeleteFriend.
func (mr *MockUserClientMockRecorder) DeleteFriend(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFriend", reflect.TypeOf((*MockUserClient)(nil).DeleteFriend), varargs...)
}

// DeleteOutgoingFriendRequest mocks base method.
func (m *MockUserClient) DeleteOutgoingFriendRequest(ctx context.Context, in *userv1.DeleteOutgoingFriendRequestRequest, opts ...grpc.CallOption) (*userv1.DeleteOutgoingFriendRequestResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOutgoingFriendRequest", varargs...)
	ret0, _ := ret[0].(*userv1.DeleteOutgoingFriendRequestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOutgoingFriendRequest indicates an expected call of DeleteOutgoingFriendRequest.
func (mr *MockUserClientMockRecorder) DeleteOutgoingFriendRequest(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOutgoingFriendRequest", reflect.TypeOf((*MockUserClient)(nil).DeleteOutgoingFriendRequest), varargs...)
}

// GetContinueWatching mocks base method.
func (m *MockUserClient) GetContinueWatching(ctx context.Context, in *moviev1.GetContinueWatchingRequest, opts ...grpc.CallOption) (*moviev1.GetContinueWatchingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetContinueWatching", varargs...)
	ret0, _ := ret[0].(*moviev1.GetContinueWatchingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContinueWatching indicates an expected call of GetContinueWatching.
func (mr *MockUserClientMockRecorder) GetContinueWatching(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContinueWatching", reflect.TypeOf((*MockUserClient)(nil).GetContinueWatching), varargs...)
}

// GetFavorites mocks base method.
func (m *MockUserClient) GetFavorites(ctx context.Context, in *userv1.GetFavoritesRequest, opts ...grpc.CallOption) (*userv1.GetFavoritesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFavorites", varargs...)
	ret0, _ := ret[0].(*userv1.GetFavoritesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavorites indicates an expected call of GetFavorites.
func (mr *MockUserClientMockRecorder) GetFavorites(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavorites", reflect.TypeOf((*MockUserClient)(nil).GetFavorites), varargs...)
}

// GetFriendRequests mocks base method.
func (m *MockUserClient) GetFriendRequests(ctx context.Context, in *userv1.GetFriendRequestsRequest, opts ...grpc.CallOption) (*userv1.GetFriendRequestsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFriendRequests", varargs...)
	ret0, _ := ret[0].(*userv1.GetFriendRequestsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendRequests indicates an expected call of GetFriendRequests.
func (mr *MockUserClientMockRecorder) GetFriendRequests(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendRequests", reflect.TypeOf((*MockUserClient)(nil).GetFriendRequests), varargs...)
}

// GetFriendsList mocks base method.
func (m *MockUserClient) GetFriendsList(ctx context.Context, in *userv1.GetFriendsListRequest, opts ...grpc.CallOption) (*userv1.GetFriendsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFriendsList", varargs...)
	ret0, _ := ret[0].(*userv1.GetFriendsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendsList indicates an expected call of GetFriendsList.
func (mr *MockUserClientMockRecorder) GetFriendsList(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendsList", reflect.TypeOf((*MockUserClient)(nil).GetFriendsList), varargs...)
}

// GetMoviesByIDs mocks base method.
func (m *MockUserClient) GetMoviesByIDs(ctx context.Context, in *moviev1.GetMoviesByIDsRequest, opts ...grpc.CallOption) (*moviev1.GetMoviesByIDsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMoviesByIDs", varargs...)
	ret0, _ := ret[0].(*moviev1.GetMoviesByIDsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMoviesByIDs indicates an expected call of GetMoviesByIDs.
func (mr *MockUserClientMockRecorder) GetMoviesByIDs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoviesByIDs", reflect.TypeOf((*MockUserClient)(nil).GetMoviesByIDs), varargs...)
}

// GetProfile mocks base method.
func (m *MockUserClient) GetProfile(ctx context.Context, in *userv1.GetProfileRequest, opts ...grpc.CallOption) (*userv1.GetProfileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProfile", varargs...)
	ret0, _ := ret[0].(*userv1.GetProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockUserClientMockRecorder) GetProfile(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockUserClient)(nil).GetProfile), varargs...)
}

// GetSupportFileURL mocks base method.
func (m *MockUserClient) GetSupportFileURL(ctx context.Context, in *supportv1.GetSupportFileURLRequest, opts ...grpc.CallOption) (*supportv1.GetSupportFileURLResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSupportFileURL", varargs...)
	ret0, _ := ret[0].(*supportv1.GetSupportFileURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupportFileURL indicates an expected call of GetSupportFileURL.
func (mr *MockUserClientMockRecorder) GetSupportFileURL(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportFileURL", reflect.TypeOf((*MockUserClient)(nil).GetSupportFileURL), varargs...)
}

// GetTicketMessages mocks base method.
func (m *MockUserClient) GetTicketMessages(ctx context.Context, in *supportv1.GetTicketMessagesRequest, opts ...grpc.CallOption) (*supportv1.TicketMessagesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTicketMessages", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketMessagesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketMessages indicates an expected call of GetTicketMessages.
func (mr *MockUserClientMockRecorder) GetTicketMessages(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketMessages", reflect.TypeOf((*MockUserClient)(nil).GetTicketMessages), varargs...)
}

// GetTicketStatistics mocks base method.
func (m *MockUserClient) GetTicketStatistics(ctx context.Context, in *supportv1.GetTicketStatisticsRequest, opts ...grpc.CallOption) (*supportv1.TicketStatisticsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTicketStatistics", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketStatisticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketStatistics indicates an expected call of GetTicketStatistics.
func (mr *MockUserClientMockRecorder) GetTicketStatistics(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketStatistics", reflect.TypeOf((*MockUserClient)(nil).GetTicketStatistics), varargs...)
}

// GetTickets mocks base method.
func (m *MockUserClient) GetTickets(ctx context.Context, in *supportv1.GetTicketsRequest, opts ...grpc.CallOption) (*supportv1.TicketsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTickets", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickets indicates an expected call of GetTickets.
func (mr *MockUserClientMockRecorder) GetTickets(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickets", reflect.TypeOf((*MockUserClient)(nil).GetTickets), varargs...)
}

// GetWatchHistory mocks base method.
func (m *MockUserClient) GetWatchHistory(ctx context.Context, in *moviev1.GetWatchHistoryRequest, opts ...grpc.CallOption) (*moviev1.GetWatchHistoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWatchHistory", varargs...)
	ret0, _ := ret[0].(*moviev1.GetWatchHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatchHistory indicates an expected call of GetWatchHistory.
func (mr *MockUserClientMockRecorder) GetWatchHistory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchHistory", reflect.TypeOf((*MockUserClient)(nil).GetWatchHistory), varargs...)
}

// RespondToFriendRequest mocks base method.
func (m *MockUserClient) RespondToFriendRequest(ctx context.Context, in *userv1.RespondToFriendRequestRequest, opts ...grpc.CallOption) (*userv1.RespondToFriendRequestResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RespondToFriendRequest", varargs...)
	ret0, _ := ret[0].(*userv1.RespondToFriendRequestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RespondToFriendRequest indicates an expected call of RespondToFriendRequest.
func (mr *MockUserClientMockRecorder) RespondToFriendRequest(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondToFriendRequest", reflect.TypeOf((*MockUserClient)(nil).RespondToFriendRequest), varargs...)
}

// SearchUsers mocks base method.
func (m *MockUserClient) SearchUsers(ctx context.Context, in *userv1.SearchUsersRequest, opts ...grpc.CallOption) (*userv1.SearchUsersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchUsers", varargs...)
	ret0, _ := ret[0].(*userv1.SearchUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockUserClientMockRecorder) SearchUsers(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockUserClient)(nil).SearchUsers), varargs...)
}

// SearchUsersByEmail mocks base method.
func (m *MockUserClient) SearchUsersByEmail(ctx context.Context, in *userv1.SearchUsersByEmailRequest, opts ...grpc.CallOption) (*userv1.SearchUsersByEmailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchUsersByEmail", varargs...)
	ret0, _ := ret[0].(*userv1.SearchUsersByEmailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersByEmail indicates an expected call of SearchUsersByEmail.
func (mr *MockUserClientMockRecorder) SearchUsersByEmail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersByEmail", reflect.TypeOf((*MockUserClient)(nil).SearchUsersByEmail), varargs...)
}

// SendFriendRequest mocks base method.
func (m *MockUserClient) SendFriendRequest(ctx context.Context, in *userv1.SendFriendRequestRequest, opts ...grpc.CallOption) (*userv1.SendFriendRequestResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendFriendRequest", varargs...)
	ret0, _ := ret[0].(*userv1.SendFriendRequestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFriendRequest indicates an expected call of SendFriendRequest.
func (mr *MockUserClientMockRecorder) SendFriendRequest(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFriendRequest", reflect.TypeOf((*MockUserClient)(nil).SendFriendRequest), varargs...)
}

// SubscribeTicket mocks base method.
func (m *MockUserClient) SubscribeTicket(ctx context.Context, in *supportv1.SubscribeTicketRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[supportv1.TicketEvent], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeTicket", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[supportv1.TicketEvent])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeTicket indicates an expected call of SubscribeTicket.
func (mr *MockUserClientMockRecorder) SubscribeTicket(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeTicket", reflect.TypeOf((*MockUserClient)(nil).SubscribeTicket), varargs...)
}

// ToggleFavorite mocks base method.
func (m *MockUserClient) ToggleFavorite(ctx context.Context, in *userv1.ToggleFavoriteRequest, opts ...grpc.CallOption) (*userv1.ToggleFavoriteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ToggleFavorite", varargs...)
	ret0, _ := ret[0].(*userv1.ToggleFavoriteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleFavorite indicates an expected call of ToggleFavorite.
func (mr *MockUserClientMockRecorder) ToggleFavorite(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleFavorite", reflect.TypeOf((*MockUserClient)(nil).ToggleFavorite), varargs...)
}

// UpdateProfile mocks base method.
func (m *MockUserClient) UpdateProfile(ctx context.Context, in *userv1.UpdateProfileRequest, opts ...grpc.CallOption) (*userv1.UpdateProfileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProfile", varargs...)
	ret0, _ := ret[0].(*userv1.UpdateProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserClientMockRecorder) UpdateProfile(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserClient)(nil).UpdateProfile), varargs...)
}

// UpdateTicket mocks base method.
func (m *MockUserClient) UpdateTicket(ctx context.Context, in *supportv1.UpdateTicketRequest, opts ...grpc.CallOption) (*supportv1.TicketResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateTicket", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTicket indicates an expected call of UpdateTicket.
func (mr *MockUserClientMockRecorder) UpdateTicket(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTicket", reflect.TypeOf((*MockUserClient)(nil).UpdateTicket), varargs...)
}

// UploadSupportFile mocks base method.
func (m *MockUserClient) UploadSupportFile(ctx context.Context, in *supportv1.UploadSupportFileRequest, opts ...grpc.CallOption) (*supportv1.UploadSupportFileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadSupportFile", varargs...)
	ret0, _ := ret[0].(*supportv1.UploadSupportFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadSupportFile indicates an expected call of UploadSupportFile.
func (mr *MockUserClientMockRecorder) UploadSupportFile(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadSupportFile", reflect.TypeOf((*MockUserClient)(nil).UploadSupportFile), varargs...)
}

// MockmovieRPC is a mock of movieRPC interface.
type MockmovieRPC struct {
	ctrl     *gomock.Controller
	recorder *MockmovieRPCMockRecorder
	isgomock struct{}
}

// MockmovieRPCMockRecorder is the mock recorder for MockmovieRPC.
type MockmovieRPCMockRecorder struct {
	mock *MockmovieRPC
}

// NewMockmovieRPC creates a new mock instance.
func NewMockmovieRPC(ctrl *gomock.Controller) *MockmovieRPC {
	mock := &MockmovieRPC{ctrl: ctrl}
	mock.recorder = &MockmovieRPCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmovieRPC) EXPECT() *MockmovieRPCMockRecorder {
	return m.recorder
}

// GetContinueWatching mocks base method.
func (m *MockmovieRPC) GetContinueWatching(ctx context.Context, in *moviev1.GetContinueWatchingRequest, opts ...grpc.CallOption) (*moviev1.GetContinueWatchingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetContinueWatching", varargs...)
	ret0, _ := ret[0].(*moviev1.GetContinueWatchingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContinueWatching indicates an expected call of GetContinueWatching.
func (mr *MockmovieRPCMockRecorder) GetContinueWatching(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContinueWatching", reflect.TypeOf((*MockmovieRPC)(nil).GetContinueWatching), varargs...)
}

// GetMoviesByIDs mocks base method.
func (m *MockmovieRPC) GetMoviesByIDs(ctx context.Context, in *moviev1.GetMoviesByIDsRequest, opts ...grpc.CallOption) (*moviev1.GetMoviesByIDsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMoviesByIDs", varargs...)
	ret0, _ := ret[0].(*moviev1.GetMoviesByIDsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMoviesByIDs indicates an expected call of GetMoviesByIDs.
func (mr *MockmovieRPCMockRecorder) GetMoviesByIDs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoviesByIDs", reflect.TypeOf((*MockmovieRPC)(nil).GetMoviesByIDs), varargs...)
}

// GetWatchHistory mocks base method.
func (m *MockmovieRPC) GetWatchHistory(ctx context.Context, in *moviev1.GetWatchHistoryRequest, opts ...grpc.CallOption) (*moviev1.GetWatchHistoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWatchHistory", varargs...)
	ret0, _ := ret[0].(*moviev1.GetWatchHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatchHistory indicates an expected call of GetWatchHistory.
func (mr *MockmovieRPCMockRecorder) GetWatchHistory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchHistory", reflect.TypeOf((*MockmovieRPC)(nil).GetWatchHistory), varargs...)
}

// MocksupportRPC is a mock of supportRPC interface.
type MocksupportRPC struct {
	ctrl     *gomock.Controller
	recorder *MocksupportRPCMockRecorder
	isgomock struct{}
}

// MocksupportRPCMockRecorder is the mock recorder for MocksupportRPC.
type MocksupportRPCMockRecorder struct {
	mock *MocksupportRPC
}

// NewMocksupportRPC creates a new mock instance.
func NewMocksupportRPC(ctrl *gomock.Controller) *MocksupportRPC {
	mock := &MocksupportRPC{ctrl: ctrl}
	mock.recorder = &MocksupportRPCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksupportRPC) EXPECT() *MocksupportRPCMockRecorder {
	return m.recorder
}

// CreateTicket mocks base method.
func (m *MocksupportRPC) CreateTicket(ctx context.Context, in *supportv1.CreateTicketRequest, opts ...grpc.CallOption) (*supportv1.TicketResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTicket", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicket indicates an expected call of CreateTicket.
func (mr *MocksupportRPCMockRecorder) CreateTicket(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicket", reflect.TypeOf((*MocksupportRPC)(nil).CreateTicket), varargs...)
}

// CreateTicketMessage mocks base method.
func (m *MocksupportRPC) CreateTicketMessage(ctx context.Context, in *supportv1.CreateTicketMessageRequest, opts ...grpc.CallOption) (*supportv1.TicketMessageResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTicketMessage", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicketMessage indicates an expected call of CreateTicketMessage.
func (mr *MocksupportRPCMockRecorder) CreateTicketMessage(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicketMessage", reflect.TypeOf((*MocksupportRPC)(nil).CreateTicketMessage), varargs...)
}

// GetSupportFileURL mocks base method.
func (m *MocksupportRPC) GetSupportFileURL(ctx context.Context, in *supportv1.GetSupportFileURLRequest, opts ...grpc.CallOption) (*supportv1.GetSupportFileURLResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSupportFileURL", varargs...)
	ret0, _ := ret[0].(*supportv1.GetSupportFileURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupportFileURL indicates an expected call of GetSupportFileURL.
func (mr *MocksupportRPCMockRecorder) GetSupportFileURL(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportFileURL", reflect.TypeOf((*MocksupportRPC)(nil).GetSupportFileURL), varargs...)
}

// GetTicketMessages mocks base method.
func (m *MocksupportRPC) GetTicketMessages(ctx context.Context, in *supportv1.GetTicketMessagesRequest, opts ...grpc.CallOption) (*supportv1.TicketMessagesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTicketMessages", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketMessagesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketMessages indicates an expected call of GetTicketMessages.
func (mr *MocksupportRPCMockRecorder) GetTicketMessages(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketMessages", reflect.TypeOf((*MocksupportRPC)(nil).GetTicketMessages), varargs...)
}

// GetTicketStatistics mocks base method.
func (m *MocksupportRPC) GetTicketStatistics(ctx context.Context, in *supportv1.GetTicketStatisticsRequest, opts ...grpc.CallOption) (*supportv1.TicketStatisticsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTicketStatistics", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketStatisticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketStatistics indicates an expected call of GetTicketStatistics.
func (mr *MocksupportRPCMockRecorder) GetTicketStatistics(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketStatistics", reflect.TypeOf((*MocksupportRPC)(nil).GetTicketStatistics), varargs...)
}

// GetTickets mocks base method.
func (m *MocksupportRPC) GetTickets(ctx context.Context, in *supportv1.GetTicketsRequest, opts ...grpc.CallOption) (*supportv1.TicketsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTickets", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickets indicates an expected call of GetTickets.
func (mr *MocksupportRPCMockRecorder) GetTickets(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickets", reflect.TypeOf((*MocksupportRPC)(nil).GetTickets), varargs...)
}

// SubscribeTicket mocks base method.
func (m *MocksupportRPC) SubscribeTicket(ctx context.Context, in *supportv1.SubscribeTicketRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[supportv1.TicketEvent], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeTicket", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[supportv1.TicketEvent])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeTicket indicates an expected call of SubscribeTicket.
func (mr *MocksupportRPCMockRecorder) SubscribeTicket(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeTicket", reflect.TypeOf((*MocksupportRPC)(nil).SubscribeTicket), varargs...)
}

// UpdateTicket mocks base method.
func (m *MocksupportRPC) UpdateTicket(ctx context.Context, in *supportv1.UpdateTicketRequest, opts ...grpc.CallOption) (*supportv1.TicketResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateTicket", varargs...)
	ret0, _ := ret[0].(*supportv1.TicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTicket indicates an expected call of UpdateTicket.
func (mr *MocksupportRPCMockRecorder) UpdateTicket(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTicket", reflect.TypeOf((*MocksupportRPC)(nil).UpdateTicket), varargs...)
}

// UploadSupportFile mocks base method.
func (m *MocksupportRPC) UploadSupportFile(ctx context.Context, in *supportv1.UploadSupportFileRequest, opts ...grpc.CallOption) (*supportv1.UploadSupportFileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadSupportFile", varargs...)
	ret0, _ := ret[0].(*supportv1.UploadSupportFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadSupportFile indicates an expected call of UploadSupportFile.
func (mr *MocksupportRPCMockRecorder) UploadSupportFile(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadSupportFile", reflect.TypeOf((*MocksupportRPC)(nil).UploadSupportFile), varargs...)
}
