// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination=./mocks/movie_repo_mock.go -package=mocks MovieRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_VKino/internal/app/movie-service/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMovieRepo is a mock of MovieRepo interface.
type MockMovieRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMovieRepoMockRecorder
	isgomock struct{}
}

// MockMovieRepoMockRecorder is the mock recorder for MockMovieRepo.
type MockMovieRepoMockRecorder struct {
	mock *MockMovieRepo
}

// NewMockMovieRepo creates a new mock instance.
func NewMockMovieRepo(ctrl *gomock.Controller) *MockMovieRepo {
	mock := &MockMovieRepo{ctrl: ctrl}
	mock.recorder = &MockMovieRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieRepo) EXPECT() *MockMovieRepoMockRecorder {
	return m.recorder
}

// GetActorByID mocks base method.
func (m *MockMovieRepo) GetActorByID(ctx context.Context, actorID int64) (*domain.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorByID", ctx, actorID)
	ret0, _ := ret[0].(*domain.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorByID indicates an expected call of GetActorByID.
func (mr *MockMovieRepoMockRecorder) GetActorByID(ctx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorByID", reflect.TypeOf((*MockMovieRepo)(nil).GetActorByID), ctx, actorID)
}

// GetAllSelections mocks base method.
func (m *MockMovieRepo) GetAllSelections(ctx context.Context) ([]domain.Selection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSelections", ctx)
	ret0, _ := ret[0].([]domain.Selection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSelections indicates an expected call of GetAllSelections.
func (mr *MockMovieRepoMockRecorder) GetAllSelections(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSelections", reflect.TypeOf((*MockMovieRepo)(nil).GetAllSelections), ctx)
}

// GetContinueWatching mocks base method.
func (m *MockMovieRepo) GetContinueWatching(ctx context.Context, userID int64, limit int32) ([]domain.WatchProgressItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContinueWatching", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.WatchProgressItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContinueWatching indicates an expected call of GetContinueWatching.
func (mr *MockMovieRepoMockRecorder) GetContinueWatching(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContinueWatching", reflect.TypeOf((*MockMovieRepo)(nil).GetContinueWatching), ctx, userID, limit)
}

// GetEpisodePlayback mocks base method.
func (m *MockMovieRepo) GetEpisodePlayback(ctx context.Context, episodeID int64) (*domain.Episode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpisodePlayback", ctx, episodeID)
	ret0, _ := ret[0].(*domain.Episode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpisodePlayback indicates an expected call of GetEpisodePlayback.
func (mr *MockMovieRepoMockRecorder) GetEpisodePlayback(ctx, episodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpisodePlayback", reflect.TypeOf((*MockMovieRepo)(nil).GetEpisodePlayback), ctx, episodeID)
}

// GetEpisodeProgress mocks base method.
func (m *MockMovieRepo) GetEpisodeProgress(ctx context.Context, userID, episodeID int64) (domain.EpisodeProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpisodeProgress", ctx, userID, episodeID)
	ret0, _ := ret[0].(domain.EpisodeProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpisodeProgress indicates an expected call of GetEpisodeProgress.
func (mr *MockMovieRepoMockRecorder) GetEpisodeProgress(ctx, userID, episodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpisodeProgress", reflect.TypeOf((*MockMovieRepo)(nil).GetEpisodeProgress), ctx, userID, episodeID)
}

// GetMovieByID mocks base method.
func (m *MockMovieRepo) GetMovieByID(ctx context.Context, movieID int64) (*domain.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovieByID", ctx, movieID)
	ret0, _ := ret[0].(*domain.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovieByID indicates an expected call of GetMovieByID.
func (mr *MockMovieRepoMockRecorder) GetMovieByID(ctx, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovieByID", reflect.TypeOf((*MockMovieRepo)(nil).GetMovieByID), ctx, movieID)
}

// GetSelectionByTitle mocks base method.
func (m *MockMovieRepo) GetSelectionByTitle(ctx context.Context, title string) (domain.Selection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelectionByTitle", ctx, title)
	ret0, _ := ret[0].(domain.Selection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectionByTitle indicates an expected call of GetSelectionByTitle.
func (mr *MockMovieRepoMockRecorder) GetSelectionByTitle(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectionByTitle", reflect.TypeOf((*MockMovieRepo)(nil).GetSelectionByTitle), ctx, title)
}

// GetWatchHistory mocks base method.
func (m *MockMovieRepo) GetWatchHistory(ctx context.Context, userID int64, limit int32, minProgress float64) ([]domain.WatchProgressItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatchHistory", ctx, userID, limit, minProgress)
	ret0, _ := ret[0].([]domain.WatchProgressItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatchHistory indicates an expected call of GetWatchHistory.
func (mr *MockMovieRepoMockRecorder) GetWatchHistory(ctx, userID, limit, minProgress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchHistory", reflect.TypeOf((*MockMovieRepo)(nil).GetWatchHistory), ctx, userID, limit, minProgress)
}

// IsFavorite mocks base method.
func (m *MockMovieRepo) IsFavorite(ctx context.Context, userID, movieID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFavorite", ctx, userID, movieID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFavorite indicates an expected call of IsFavorite.
func (mr *MockMovieRepoMockRecorder) IsFavorite(ctx, userID, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFavorite", reflect.TypeOf((*MockMovieRepo)(nil).IsFavorite), ctx, userID, movieID)
}

// SaveEpisodeProgress mocks base method.
func (m *MockMovieRepo) SaveEpisodeProgress(ctx context.Context, userID, episodeID, positionSec int64) (domain.EpisodeProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEpisodeProgress", ctx, userID, episodeID, positionSec)
	ret0, _ := ret[0].(domain.EpisodeProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveEpisodeProgress indicates an expected call of SaveEpisodeProgress.
func (mr *MockMovieRepoMockRecorder) SaveEpisodeProgress(ctx, userID, episodeID, positionSec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEpisodeProgress", reflect.TypeOf((*MockMovieRepo)(nil).SaveEpisodeProgress), ctx, userID, episodeID, positionSec)
}

// SearchMovies mocks base method.
func (m *MockMovieRepo) SearchMovies(ctx context.Context, query string) ([]domain.MovieCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMovies", ctx, query)
	ret0, _ := ret[0].([]domain.MovieCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMovies indicates an expected call of SearchMovies.
func (mr *MockMovieRepoMockRecorder) SearchMovies(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMovies", reflect.TypeOf((*MockMovieRepo)(nil).SearchMovies), ctx, query)
}
