// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  domain

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( ChangePasswordRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ChangePasswordRequest ) UnmarshalJSON([]byte) error { return nil }
func ( ChangePasswordRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ChangePasswordRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ChangePasswordRequest *ChangePasswordRequest

func ( SupportCreateTicketMessageRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SupportCreateTicketMessageRequest ) UnmarshalJSON([]byte) error { return nil }
func ( SupportCreateTicketMessageRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SupportCreateTicketMessageRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SupportCreateTicketMessageRequest *SupportCreateTicketMessageRequest

func ( SupportCreateTicketRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SupportCreateTicketRequest ) UnmarshalJSON([]byte) error { return nil }
func ( SupportCreateTicketRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SupportCreateTicketRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SupportCreateTicketRequest *SupportCreateTicketRequest

func ( SupportGetTicketsRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SupportGetTicketsRequest ) UnmarshalJSON([]byte) error { return nil }
func ( SupportGetTicketsRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SupportGetTicketsRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SupportGetTicketsRequest *SupportGetTicketsRequest

func ( SupportUpdateTicketRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SupportUpdateTicketRequest ) UnmarshalJSON([]byte) error { return nil }
func ( SupportUpdateTicketRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SupportUpdateTicketRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SupportUpdateTicketRequest *SupportUpdateTicketRequest
