// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson78e1d018DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain(in *jlexer.Lexer, out *PartyRoomCardHTTP) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "name":
			out.Name = string(in.String())
		case "visibility":
			out.Visibility = string(in.String())
		case "invite_link":
			out.InviteLink = string(in.String())
		case "host_user_id":
			out.HostUserID = int64(in.Int64())
		case "host_name":
			out.HostName = string(in.String())
		case "participants_count":
			out.ParticipantsCount = int32(in.Int32())
		case "playback":
			if in.IsNull() {
				in.Skip()
				out.Playback = nil
			} else {
				if out.Playback == nil {
					out.Playback = new(PartyPlaybackStateHTTP)
				}
				(*out.Playback).UnmarshalEasyJSON(in)
			}
		case "updated_at":
			out.UpdatedAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson78e1d018EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain(out *jwriter.Writer, in PartyRoomCardHTTP) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"visibility\":"
		out.RawString(prefix)
		out.String(string(in.Visibility))
	}
	{
		const prefix string = ",\"invite_link\":"
		out.RawString(prefix)
		out.String(string(in.InviteLink))
	}
	{
		const prefix string = ",\"host_user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.HostUserID))
	}
	{
		const prefix string = ",\"host_name\":"
		out.RawString(prefix)
		out.String(string(in.HostName))
	}
	{
		const prefix string = ",\"participants_count\":"
		out.RawString(prefix)
		out.Int32(int32(in.ParticipantsCount))
	}
	if in.Playback != nil {
		const prefix string = ",\"playback\":"
		out.RawString(prefix)
		(*in.Playback).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartyRoomCardHTTP) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson78e1d018EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartyRoomCardHTTP) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson78e1d018EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartyRoomCardHTTP) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson78e1d018DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartyRoomCardHTTP) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson78e1d018DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain(l, v)
}
func easyjson78e1d018DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain1(in *jlexer.Lexer, out *PartyPlaybackStateHTTP) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "movie_id":
			out.MovieID = int64(in.Int64())
		case "movie_title":
			if in.IsNull() {
				in.Skip()
				out.MovieTitle = nil
			} else {
				if out.MovieTitle == nil {
					out.MovieTitle = new(string)
				}
				*out.MovieTitle = string(in.String())
			}
		case "episode_id":
			out.EpisodeID = int64(in.Int64())
		case "img_url":
			if in.IsNull() {
				in.Skip()
				out.ImgURL = nil
			} else {
				if out.ImgURL == nil {
					out.ImgURL = new(string)
				}
				*out.ImgURL = string(in.String())
			}
		case "playback_url":
			out.PlaybackURL = string(in.String())
		case "duration_seconds":
			out.DurationSeconds = int64(in.Int64())
		case "position_seconds":
			out.PositionSeconds = int64(in.Int64())
		case "status":
			out.Status = string(in.String())
		case "updated_at":
			out.UpdatedAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson78e1d018EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain1(out *jwriter.Writer, in PartyPlaybackStateHTTP) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"movie_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.MovieID))
	}
	{
		const prefix string = ",\"movie_title\":"
		out.RawString(prefix)
		if in.MovieTitle == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.MovieTitle))
		}
	}
	{
		const prefix string = ",\"episode_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.EpisodeID))
	}
	{
		const prefix string = ",\"img_url\":"
		out.RawString(prefix)
		if in.ImgURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ImgURL))
		}
	}
	if in.PlaybackURL != "" {
		const prefix string = ",\"playback_url\":"
		out.RawString(prefix)
		out.String(string(in.PlaybackURL))
	}
	{
		const prefix string = ",\"duration_seconds\":"
		out.RawString(prefix)
		out.Int64(int64(in.DurationSeconds))
	}
	{
		const prefix string = ",\"position_seconds\":"
		out.RawString(prefix)
		out.Int64(int64(in.PositionSeconds))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartyPlaybackStateHTTP) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson78e1d018EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartyPlaybackStateHTTP) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson78e1d018EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartyPlaybackStateHTTP) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson78e1d018DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartyPlaybackStateHTTP) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson78e1d018DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain1(l, v)
}
func easyjson78e1d018DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain2(in *jlexer.Lexer, out *PartyOverviewResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "active_rooms":
			if in.IsNull() {
				in.Skip()
				out.ActiveRooms = nil
			} else {
				in.Delim('[')
				if out.ActiveRooms == nil {
					if !in.IsDelim(']') {
						out.ActiveRooms = make([]PartyRoomCardHTTP, 0, 0)
					} else {
						out.ActiveRooms = []PartyRoomCardHTTP{}
					}
				} else {
					out.ActiveRooms = (out.ActiveRooms)[:0]
				}
				for !in.IsDelim(']') {
					var v1 PartyRoomCardHTTP
					(v1).UnmarshalEasyJSON(in)
					out.ActiveRooms = append(out.ActiveRooms, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "my_rooms":
			if in.IsNull() {
				in.Skip()
				out.MyRooms = nil
			} else {
				in.Delim('[')
				if out.MyRooms == nil {
					if !in.IsDelim(']') {
						out.MyRooms = make([]PartyRoomCardHTTP, 0, 0)
					} else {
						out.MyRooms = []PartyRoomCardHTTP{}
					}
				} else {
					out.MyRooms = (out.MyRooms)[:0]
				}
				for !in.IsDelim(']') {
					var v2 PartyRoomCardHTTP
					(v2).UnmarshalEasyJSON(in)
					out.MyRooms = append(out.MyRooms, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "featured_rooms":
			if in.IsNull() {
				in.Skip()
				out.FeaturedRooms = nil
			} else {
				in.Delim('[')
				if out.FeaturedRooms == nil {
					if !in.IsDelim(']') {
						out.FeaturedRooms = make([]PartyRoomCardHTTP, 0, 0)
					} else {
						out.FeaturedRooms = []PartyRoomCardHTTP{}
					}
				} else {
					out.FeaturedRooms = (out.FeaturedRooms)[:0]
				}
				for !in.IsDelim(']') {
					var v3 PartyRoomCardHTTP
					(v3).UnmarshalEasyJSON(in)
					out.FeaturedRooms = append(out.FeaturedRooms, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson78e1d018EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain2(out *jwriter.Writer, in PartyOverviewResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"active_rooms\":"
		out.RawString(prefix[1:])
		if in.ActiveRooms == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.ActiveRooms {
				if v4 > 0 {
					out.RawByte(',')
				}
				(v5).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"my_rooms\":"
		out.RawString(prefix)
		if in.MyRooms == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.MyRooms {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"featured_rooms\":"
		out.RawString(prefix)
		if in.FeaturedRooms == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.FeaturedRooms {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartyOverviewResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson78e1d018EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartyOverviewResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson78e1d018EncodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartyOverviewResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson78e1d018DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartyOverviewResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson78e1d018DecodeGithubComGoParkMailRu20261VKinoInternalAppApiGatewayDomain2(l, v)
}
