// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/movie/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=./internal/app/movie/repository/repository.go -destination=./internal/app/movie/usecase/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_VKino/internal/app/movie/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMovieRepo is a mock of MovieRepo interface.
type MockMovieRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMovieRepoMockRecorder
	isgomock struct{}
}

// MockMovieRepoMockRecorder is the mock recorder for MockMovieRepo.
type MockMovieRepoMockRecorder struct {
	mock *MockMovieRepo
}

// NewMockMovieRepo creates a new mock instance.
func NewMockMovieRepo(ctrl *gomock.Controller) *MockMovieRepo {
	mock := &MockMovieRepo{ctrl: ctrl}
	mock.recorder = &MockMovieRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieRepo) EXPECT() *MockMovieRepoMockRecorder {
	return m.recorder
}

// GetActorByID mocks base method.
func (m *MockMovieRepo) GetActorByID(ctx context.Context, id int64) (domain.ActorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorByID", ctx, id)
	ret0, _ := ret[0].(domain.ActorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorByID indicates an expected call of GetActorByID.
func (mr *MockMovieRepoMockRecorder) GetActorByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorByID", reflect.TypeOf((*MockMovieRepo)(nil).GetActorByID), ctx, id)
}

// GetAllSelections mocks base method.
func (m *MockMovieRepo) GetAllSelections(ctx context.Context) ([]domain.SelectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSelections", ctx)
	ret0, _ := ret[0].([]domain.SelectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSelections indicates an expected call of GetAllSelections.
func (mr *MockMovieRepoMockRecorder) GetAllSelections(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSelections", reflect.TypeOf((*MockMovieRepo)(nil).GetAllSelections), ctx)
}

// GetEpisodePlayback mocks base method.
func (m *MockMovieRepo) GetEpisodePlayback(ctx context.Context, episodeID int64) (domain.EpisodePlaybackResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpisodePlayback", ctx, episodeID)
	ret0, _ := ret[0].(domain.EpisodePlaybackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpisodePlayback indicates an expected call of GetEpisodePlayback.
func (mr *MockMovieRepoMockRecorder) GetEpisodePlayback(ctx, episodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpisodePlayback", reflect.TypeOf((*MockMovieRepo)(nil).GetEpisodePlayback), ctx, episodeID)
}

// GetEpisodesByMovieID mocks base method.
func (m *MockMovieRepo) GetEpisodesByMovieID(ctx context.Context, movieID int64) ([]domain.EpisodeItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpisodesByMovieID", ctx, movieID)
	ret0, _ := ret[0].([]domain.EpisodeItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpisodesByMovieID indicates an expected call of GetEpisodesByMovieID.
func (mr *MockMovieRepoMockRecorder) GetEpisodesByMovieID(ctx, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpisodesByMovieID", reflect.TypeOf((*MockMovieRepo)(nil).GetEpisodesByMovieID), ctx, movieID)
}

// GetMovieByID mocks base method.
func (m *MockMovieRepo) GetMovieByID(ctx context.Context, id int64) (domain.MovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovieByID", ctx, id)
	ret0, _ := ret[0].(domain.MovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovieByID indicates an expected call of GetMovieByID.
func (mr *MockMovieRepoMockRecorder) GetMovieByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovieByID", reflect.TypeOf((*MockMovieRepo)(nil).GetMovieByID), ctx, id)
}

// GetSelectionByTitle mocks base method.
func (m *MockMovieRepo) GetSelectionByTitle(ctx context.Context, title string) (domain.SelectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelectionByTitle", ctx, title)
	ret0, _ := ret[0].(domain.SelectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectionByTitle indicates an expected call of GetSelectionByTitle.
func (mr *MockMovieRepoMockRecorder) GetSelectionByTitle(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectionByTitle", reflect.TypeOf((*MockMovieRepo)(nil).GetSelectionByTitle), ctx, title)
}

// GetWatchProgress mocks base method.
func (m *MockMovieRepo) GetWatchProgress(ctx context.Context, userID, episodeID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatchProgress", ctx, userID, episodeID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatchProgress indicates an expected call of GetWatchProgress.
func (mr *MockMovieRepoMockRecorder) GetWatchProgress(ctx, userID, episodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchProgress", reflect.TypeOf((*MockMovieRepo)(nil).GetWatchProgress), ctx, userID, episodeID)
}

// UpsertWatchProgress mocks base method.
func (m *MockMovieRepo) UpsertWatchProgress(ctx context.Context, userID, episodeID int64, positionSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWatchProgress", ctx, userID, episodeID, positionSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWatchProgress indicates an expected call of UpsertWatchProgress.
func (mr *MockMovieRepoMockRecorder) UpsertWatchProgress(ctx, userID, episodeID, positionSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWatchProgress", reflect.TypeOf((*MockMovieRepo)(nil).UpsertWatchProgress), ctx, userID, episodeID, positionSeconds)
}
