// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/movie/usecase/usecase.go
//
// Generated by this command:
//
//	mockgen -source=./internal/app/movie/usecase/usecase.go -destination=./internal/app/movie/usecase/mocks/usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_VKino/internal/app/movie/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetActorByID mocks base method.
func (m *MockUsecase) GetActorByID(ctx context.Context, id int64) (domain.ActorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorByID", ctx, id)
	ret0, _ := ret[0].(domain.ActorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorByID indicates an expected call of GetActorByID.
func (mr *MockUsecaseMockRecorder) GetActorByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorByID", reflect.TypeOf((*MockUsecase)(nil).GetActorByID), ctx, id)
}

// GetAllSelections mocks base method.
func (m *MockUsecase) GetAllSelections(ctx context.Context) ([]domain.SelectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSelections", ctx)
	ret0, _ := ret[0].([]domain.SelectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSelections indicates an expected call of GetAllSelections.
func (mr *MockUsecaseMockRecorder) GetAllSelections(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSelections", reflect.TypeOf((*MockUsecase)(nil).GetAllSelections), ctx)
}

// GetEpisodePlayback mocks base method.
func (m *MockUsecase) GetEpisodePlayback(ctx context.Context, episodeID, userID int64) (domain.EpisodePlaybackResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpisodePlayback", ctx, episodeID, userID)
	ret0, _ := ret[0].(domain.EpisodePlaybackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpisodePlayback indicates an expected call of GetEpisodePlayback.
func (mr *MockUsecaseMockRecorder) GetEpisodePlayback(ctx, episodeID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpisodePlayback", reflect.TypeOf((*MockUsecase)(nil).GetEpisodePlayback), ctx, episodeID, userID)
}

// GetEpisodeProgress mocks base method.
func (m *MockUsecase) GetEpisodeProgress(ctx context.Context, userID, episodeID int64) (domain.WatchProgressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpisodeProgress", ctx, userID, episodeID)
	ret0, _ := ret[0].(domain.WatchProgressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpisodeProgress indicates an expected call of GetEpisodeProgress.
func (mr *MockUsecaseMockRecorder) GetEpisodeProgress(ctx, userID, episodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpisodeProgress", reflect.TypeOf((*MockUsecase)(nil).GetEpisodeProgress), ctx, userID, episodeID)
}

// GetMovieByID mocks base method.
func (m *MockUsecase) GetMovieByID(ctx context.Context, id int64) (domain.MovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovieByID", ctx, id)
	ret0, _ := ret[0].(domain.MovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovieByID indicates an expected call of GetMovieByID.
func (mr *MockUsecaseMockRecorder) GetMovieByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovieByID", reflect.TypeOf((*MockUsecase)(nil).GetMovieByID), ctx, id)
}

// Search mocks base method.
func (m *MockUsecase) Search(ctx context.Context, query string) (domain.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query)
	ret0, _ := ret[0].(domain.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockUsecaseMockRecorder) Search(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockUsecase)(nil).Search), ctx, query)
}

// GetSelectionByTitle mocks base method.
func (m *MockUsecase) GetSelectionByTitle(ctx context.Context, title string) (domain.SelectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelectionByTitle", ctx, title)
	ret0, _ := ret[0].(domain.SelectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectionByTitle indicates an expected call of GetSelectionByTitle.
func (mr *MockUsecaseMockRecorder) GetSelectionByTitle(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectionByTitle", reflect.TypeOf((*MockUsecase)(nil).GetSelectionByTitle), ctx, title)
}

// SaveEpisodeProgress mocks base method.
func (m *MockUsecase) SaveEpisodeProgress(ctx context.Context, userID, episodeID int64, positionSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEpisodeProgress", ctx, userID, episodeID, positionSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEpisodeProgress indicates an expected call of SaveEpisodeProgress.
func (mr *MockUsecaseMockRecorder) SaveEpisodeProgress(ctx, userID, episodeID, positionSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEpisodeProgress", reflect.TypeOf((*MockUsecase)(nil).SaveEpisodeProgress), ctx, userID, episodeID, positionSeconds)
}
