BEGIN;

CREATE TABLE IF NOT EXISTS vkino_coins_pack (
    id bigint generated by default as identity primary key,
    code text NOT NULL,
    title text NOT NULL,
    coins_amount int NOT NULL,
    price_money int NOT NULL,
    sort_order int NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT vkino_coins_pack_code_unique UNIQUE (code),
    CONSTRAINT vkino_coins_pack_coins_amount_check
        CHECK (coins_amount > 0 AND coins_amount < 100000),
    CONSTRAINT vkino_coins_pack_price_money_check
        CHECK (price_money > 0)
);

INSERT INTO vkino_coins_pack (code, title, coins_amount, price_money, sort_order)
VALUES
    ('pack_50', '50 VKino coins', 50, 699, 10),
    ('pack_150', '150 VKino coins', 150, 1499, 20),
    ('pack_300', '300 VKino coins', 300, 2999, 30)
ON CONFLICT (code) DO NOTHING;

ALTER TABLE vkino_coins_history
    DROP CONSTRAINT IF EXISTS vkino_coins_history_operation_type_check;

ALTER TABLE vkino_coins_history
    ADD CONSTRAINT vkino_coins_history_operation_type_check
        CHECK (operation_type IN (
            'daily',
            'signup_bonus',
            'bet_win',
            'bet_lose',
            'bet_place',
            'purchase',
            'coins_purchase'
        ));

COMMIT;
