BEGIN;

create table if not exists friend_request (
    id bigint generated by default as identity primary key,
    from_user_id bigint not null references users(id) on delete cascade,
    to_user_id bigint not null references users(id) on delete cascade,
    status text not null default 'pending',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(from_user_id, to_user_id),
    check (from_user_id != to_user_id)
);

create trigger friend_request_set_updated_at
before update on friend_request
for each row execute function set_updated_at();

COMMIT;




