BEGIN;

create table if not exists movie_external_rating (
    id bigint generated by default as identity primary key,

    movie_id bigint not null
        references movie (id)
            on update cascade
            on delete cascade,

    source text not null
        constraint movie_external_rating_source_length
            check (char_length(source) > 0 and char_length(source) <= 64),

    value numeric(4, 2) not null
        constraint movie_external_rating_value_check
            check (value >= 0),

    scale numeric(4, 2) not null
        constraint movie_external_rating_scale_check
            check (scale > 0 and value <= scale),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint movie_external_rating_movie_source_unique unique (movie_id, source)
);

create trigger movie_external_rating_set_updated_at
before update on movie_external_rating
for each row execute function set_updated_at();

alter table user_interaction
    add column if not exists comment text null
        constraint user_interaction_comment_length
            check (comment is null or char_length(comment) <= 4096);

create table if not exists user_interaction_review_reaction (
    id bigint generated by default as identity primary key,

    review_id bigint not null
        references user_interaction (id)
            on update cascade
            on delete cascade,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete cascade,

    reaction text not null
        constraint user_interaction_review_reaction_value_check
            check (reaction in ('like', 'dislike')),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint user_interaction_review_reaction_unique unique (review_id, user_id)
);

create index if not exists user_interaction_review_reaction_review_idx
    on user_interaction_review_reaction (review_id);

create trigger user_interaction_review_reaction_set_updated_at
before update on user_interaction_review_reaction
for each row execute function set_updated_at();

COMMIT;
