BEGIN;

create table if not exists movie_external_rating (
    id bigint generated by default as identity primary key,

    movie_id bigint not null
        references movie (id)
            on update cascade
            on delete cascade,

    source text not null
        constraint movie_external_rating_source_length
            check (char_length(source) > 0 and char_length(source) <= 64),

    value numeric(4, 2) not null
        constraint movie_external_rating_value_check
            check (value >= 0),

    scale numeric(4, 2) not null
        constraint movie_external_rating_scale_check
            check (scale > 0 and value <= scale),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint movie_external_rating_movie_source_unique unique (movie_id, source)
);

create trigger movie_external_rating_set_updated_at
before update on movie_external_rating
for each row execute function set_updated_at();

COMMIT;
