BEGIN;

create table if not exists movie_external_rating (
    id bigint generated by default as identity primary key,

    movie_id bigint not null
        references movie (id)
            on update cascade
            on delete cascade,

    source text not null
        constraint movie_external_rating_source_length
            check (char_length(source) > 0 and char_length(source) <= 64),

    value numeric(4, 2) not null
        constraint movie_external_rating_value_check
            check (value >= 0),

    scale numeric(4, 2) not null
        constraint movie_external_rating_scale_check
            check (scale > 0 and value <= scale),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint movie_external_rating_movie_source_unique unique (movie_id, source)
);

create trigger movie_external_rating_set_updated_at
before update on movie_external_rating
for each row execute function set_updated_at();

with rating_seed(movie_title, imdb_value, kinopoisk_value) as (
    values
        ('Интерстеллар', 8.70, 8.60),
        ('Начало', 8.80, 8.70),
        ('Матрица', 8.70, 8.50),
        ('Гладиатор', 8.50, 8.60),
        ('Отступники', 8.50, 8.50),
        ('Одержимость', 8.50, 8.40),
        ('Остров проклятых', 8.20, 8.50),
        ('Семь', 8.60, 8.30),
        ('Пленницы', 8.20, 8.10),
        ('Социальная сеть', 7.80, 7.70),
        ('История игрушек', 8.30, 8.00),
        ('Король Лев', 8.50, 8.80),
        ('ВАЛЛ-И', 8.40, 8.30),
        ('Головоломка', 8.10, 8.10),
        ('Тайна Коко', 8.40, 8.20),
        ('Шрек', 7.90, 8.10),
        ('Как приручить дракона', 8.10, 8.20),
        ('Зверополис', 8.00, 8.30),
        ('Вверх', 8.30, 8.00),
        ('Рататуй', 8.10, 8.00),
        ('Во все тяжкие', 9.50, 8.90),
        ('Очень странные дела', 8.60, 8.40),
        ('Черное зеркало', 8.70, 8.50),
        ('Игра престолов', 9.20, 8.90),
        ('Шерлок', 9.10, 8.90),
        ('Настоящий детектив', 8.90, 8.60),
        ('Чернобыль', 9.30, 8.80),
        ('Мандалорец', 8.60, 8.00),
        ('Аркейн', 9.00, 8.70),
        ('Дом дракона', 8.40, 8.10),
        ('Долгое прощание', 7.20, 7.10),
        ('Два далеких незнакомца', 6.90, 6.60),
        ('Заикание', 7.70, 7.60),
        ('Тихий ребенок', 7.70, 7.80),
        ('Комендантский час', 7.20, 7.30),
        ('Пой', 7.90, 7.80),
        ('Кожа', 6.80, 6.50),
        ('Окно по соседству', 7.20, 7.10),
        ('Чудесная история Генри Шугара', 7.40, 7.50),
        ('Ирландское прощание', 7.30, 7.40),
        ('Гарри Поттер и философский камень', 7.70, 8.20),
        ('Один дома', 7.70, 8.30),
        ('Приключения Паддингтона 2', 7.80, 8.00),
        ('Хроники Нарнии: Лев, колдунья и волшебный шкаф', 6.90, 7.30),
        ('Малефисента', 6.90, 7.20),
        ('Мэри Поппинс возвращается', 6.70, 6.70),
        ('Джуманджи: Зов джунглей', 6.90, 6.80),
        ('Душа', 8.00, 8.30),
        ('Лука', 7.40, 7.60),
        ('Энканто', 7.20, 7.40),
        ('Одни из нас', 8.70, 8.30),
        ('Уэнсдей', 8.00, 8.00),
        ('Человек-паук: Через вселенные', 8.40, 8.40),
        ('Суперсемейка', 8.00, 8.00),
        ('В поисках Немо', 8.20, 8.10),
        ('Моана', 7.60, 8.10),
        ('Кунг-фу панда', 7.60, 7.80),
        ('Клаус', 8.20, 8.50),
        ('Оппенгеймер', 8.30, 8.30),
        ('Престиж', 8.50, 8.50),
        ('Марсианин', 8.00, 7.70),
        ('Красавица и чудовище', 7.10, 7.30),
        ('Мистер и миссис Смит', 6.50, 7.50)
)
insert into movie_external_rating (movie_id, source, value, scale)
select
    m.id,
    seeded.source,
    seeded.value,
    10.00
from rating_seed rs
join movie m on m.title = rs.movie_title
cross join lateral (
    values
        ('IMDb'::text, rs.imdb_value::numeric(4, 2)),
        ('Кинопоиск'::text, rs.kinopoisk_value::numeric(4, 2))
) as seeded(source, value)
on conflict (movie_id, source) do update
set
    value = excluded.value,
    scale = excluded.scale,
    updated_at = now();

alter table user_interaction
    add column if not exists comment text null
        constraint user_interaction_comment_length
            check (comment is null or char_length(comment) <= 4096);

with review_user_seed(email, password_hash, birthdate, avatar_file_key) as (
    values
        ('anna.viewer@seed.vkino.local', '$2y$10$gt5iYQOBFpuPgjGVW1v1duj8jCEx.8Q8OOcxT.LUNOSBQAi7w0XT.', '1996-04-12'::date, 'anna_viewer.webp'),
        ('max.cinema@seed.vkino.local', '$2y$10$gt5iYQOBFpuPgjGVW1v1duj8jCEx.8Q8OOcxT.LUNOSBQAi7w0XT.', '1992-09-03'::date, 'max_cinema.webp'),
        ('mira.family@seed.vkino.local', '$2y$10$gt5iYQOBFpuPgjGVW1v1duj8jCEx.8Q8OOcxT.LUNOSBQAi7w0XT.', '1998-01-27'::date, 'mira_family.webp'),
        ('igor.popcorn@seed.vkino.local', '$2y$10$gt5iYQOBFpuPgjGVW1v1duj8jCEx.8Q8OOcxT.LUNOSBQAi7w0XT.', '1990-11-18'::date, 'igor_popcorn.webp'),
        ('denis.scifi@seed.vkino.local', '$2y$10$gt5iYQOBFpuPgjGVW1v1duj8jCEx.8Q8OOcxT.LUNOSBQAi7w0XT.', '1989-06-01'::date, 'denis_scifi.webp'),
        ('lena.reviews@seed.vkino.local', '$2y$10$gt5iYQOBFpuPgjGVW1v1duj8jCEx.8Q8OOcxT.LUNOSBQAi7w0XT.', '1994-02-14'::date, 'lena_reviews.webp')
)
insert into users (email, password_hash, birthdate, avatar_file_key)
select
    seed.email,
    seed.password_hash,
    seed.birthdate,
    seed.avatar_file_key
from review_user_seed seed
on conflict (email) do update
set
    password_hash = excluded.password_hash,
    birthdate = excluded.birthdate,
    avatar_file_key = excluded.avatar_file_key,
    updated_at = now();

with review_seed(movie_title, user_email, rating, comment) as (
    values
        ('Оппенгеймер', 'anna.viewer@seed.vkino.local', 9.00::numeric(4, 2), 'Очень плотная историческая драма: фильм не упрощает политический контекст и при этом держит напряжение почти без передышки.'),
        ('Оппенгеймер', 'denis.scifi@seed.vkino.local', 8.70::numeric(4, 2), 'Понравилось, что картина работает и как биография, и как тревожный разговор об ответственности учёного перед миром.'),
        ('Престиж', 'max.cinema@seed.vkino.local', 9.20::numeric(4, 2), 'Один из тех фильмов, которые становятся только лучше после повторного просмотра: вся структура подчинена центральному трюку и не рассыпается.'),
        ('Престиж', 'lena.reviews@seed.vkino.local', 8.90::numeric(4, 2), 'Соперничество героев здесь страшнее любого жанрового эффекта, а финал честно расплачивается за каждую сделанную ставку.'),
        ('Марсианин', 'denis.scifi@seed.vkino.local', 8.40::numeric(4, 2), 'Отличный баланс науки, юмора и командной работы: фильм остаётся зрелищным, но не теряет ощущение реального инженерного вызова.'),
        ('Марсианин', 'igor.popcorn@seed.vkino.local', 8.10::numeric(4, 2), 'История выживания получилась лёгкой по тону, но именно за счёт этого особенно хорошо работает чувство надежды и упрямства главного героя.'),
        ('Красавица и чудовище', 'mira.family@seed.vkino.local', 7.80::numeric(4, 2), 'Очень красивая семейная сказка с бережным отношением к классической истории и хорошим музыкальным темпом.'),
        ('Красавица и чудовище', 'anna.viewer@seed.vkino.local', 7.40::numeric(4, 2), 'Больше всего сработала атмосфера замка и то, как фильм делает историю чуть человечнее, чем в совсем сказочной версии.'),
        ('Мистер и миссис Смит', 'igor.popcorn@seed.vkino.local', 7.60::numeric(4, 2), 'Химия между героями продаёт здесь почти каждую сцену: это бодрый боевик, который не забывает быть злой комедией о браке.'),
        ('Мистер и миссис Смит', 'max.cinema@seed.vkino.local', 7.10::numeric(4, 2), 'Фильм держится на харизме пары и хорошем темпе, а семейные ссоры, превращённые в экшен, до сих пор смотрятся свежо.')
)
insert into user_interaction (movie_id, user_id, rating, comment)
select
    m.id,
    u.id,
    rs.rating,
    rs.comment
from review_seed rs
join movie m on m.title = rs.movie_title
join users u on u.email = rs.user_email
on conflict (movie_id, user_id) do update
set
    rating = excluded.rating,
    comment = excluded.comment,
    updated_at = now();

create table if not exists user_interaction_review_reaction (
    id bigint generated by default as identity primary key,

    review_id bigint not null
        references user_interaction (id)
            on update cascade
            on delete cascade,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete cascade,

    reaction text not null
        constraint user_interaction_review_reaction_value_check
            check (reaction in ('like', 'dislike')),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint user_interaction_review_reaction_unique unique (review_id, user_id)
);

create index if not exists user_interaction_review_reaction_review_idx
    on user_interaction_review_reaction (review_id);

create trigger user_interaction_review_reaction_set_updated_at
before update on user_interaction_review_reaction
for each row execute function set_updated_at();

COMMIT;
