BEGIN;

alter table users
add column if not exists role text not null default 'user'
    constraint users_role_check
        check (role in ('user', 'support_l1', 'support_l2', 'admin'));

create table if not exists support_ticket (
    id bigint generated by default as identity primary key,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete cascade,

    category text not null
        constraint support_ticket_category_check
            check (category in ('bug', 'feature', 'complaint', 'question', 'other')),

    status text not null default 'open'
        constraint support_ticket_status_check
            check (status in ('open', 'in_progress', 'waiting_user', 'resolved', 'closed')),

    support_line int not null default 1
        constraint support_ticket_line_check
            check (support_line in (1, 2)),

    title text not null
        constraint support_ticket_title_length
            check (char_length(title) > 0 and char_length(title) <= 255),

    description text not null
        constraint support_ticket_description_length
            check (char_length(description) > 0 and char_length(description) <= 5000),

    attachment_file_key text null
        constraint support_ticket_attachment_file_key_length
            check (attachment_file_key is null or (char_length(attachment_file_key) > 0 and char_length(attachment_file_key) <= 1024)),

    rating int null
        constraint support_ticket_rating_check
            check (rating is null or rating between 1 and 5),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    closed_at  timestamptz null
);

create trigger support_ticket_set_updated_at
before update on support_ticket
for each row execute function set_updated_at();


create table if not exists support_ticket_message (
    id bigint generated by default as identity primary key,

    ticket_id bigint not null
        references support_ticket (id)
            on update cascade
            on delete cascade,

    sender_id bigint not null
        references users (id)
            on update cascade
            on delete cascade,

    content text null
        constraint support_ticket_message_content_length
            check (content is null or (char_length(content) > 0 and char_length(content) <= 5000)),

    content_file_key text null
        constraint support_ticket_message_content_file_key_length
            check (content_file_key is null or (char_length(content_file_key) > 0 and char_length(content_file_key) <= 1024)),

    created_at timestamptz not null default now(),

    constraint support_ticket_message_content_not_empty_check
        check (content is not null or content_file_key is not null)
);

COMMIT;