BEGIN;

-- История начисления Vkino coins
create table if not exists vkino_coins_history (
    id bigint generated by default as identity primary key,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    vkino_coins_count int not null
        constraint vkino_coins_history_vkino_coins_count_check
            check (vkino_coins_count > 0),

    -- ежедневная, выигрыш, проигрыш, покупка
    operation_type text not null default 'daily'
        constraint vkino_coins_history_operation_type_check
            check (operation_type in ('daily', 'bet_win', 'bet_lose', 'purchase')),

    description text null
        constraint vkino_coins_history_description_length
            check (description is null or char_length(description) <= 4096),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger vkino_coins_history_set_updated_at
before update on vkino_coins_history
for each row execute function set_updated_at();


-- Комната совместного просмотра
create table if not exists vkino_room (
    id bigint generated by default as identity primary key,

    -- создатель комнаты
    user_creator_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    -- текущий владелец комнаты
    user_owner_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger vkino_room_set_updated_at
before update on vkino_room
for each row execute function set_updated_at();


-- Сообщения в чате комнаты совместного просмотра
create table if not exists vkino_room_chat_message (
    id bigint generated by default as identity primary key,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    vkino_room_id bigint not null
        references vkino_room (id)
            on update cascade
            on delete cascade,

    content text null
        constraint vkino_room_chat_message_content_length
            check (content is null or (char_length(content) > 0 and char_length(content) <= 5000)),

    content_file_key text null
        constraint vkino_room_chat_message_content_file_key_length
            check (content_file_key is null or (char_length(content_file_key) > 0 and char_length(content_file_key) <= 1024)),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint vkino_room_chat_message_content_or_file_check
        check (content is not null or content_file_key is not null)
);

create trigger vkino_room_chat_message_set_updated_at
before update on vkino_room_chat_message
for each row execute function set_updated_at();


-- Ставки в чате комнаты совместного просмотра
create table if not exists vkino_room_chat_bet (
    id bigint generated by default as identity primary key,

    user_creator_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    vkino_room_id bigint not null
        references vkino_room (id)
            on update cascade
            on delete cascade,

    vkino_coins_count int not null
        constraint vkino_room_chat_bet_vkino_coins_count_check
            check (vkino_coins_count > 0),

    bet_title text not null
    constraint vkino_room_chat_bet_bet_title_length
        check (char_length(bet_title) > 0 and char_length(bet_title) <= 5000),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger vkino_room_chat_bet_set_updated_at
before update on vkino_room_chat_bet
for each row execute function set_updated_at();


-- Вариант ответа на ставке в чате комнаты совместного просмотра
create table if not exists vkino_room_chat_bet_variant (
    id bigint generated by default as identity primary key,

    vkino_room_chat_bet_id bigint not null
        references vkino_room_chat_bet (id)
            on update cascade
            on delete cascade,

    bet_variant text not null
        constraint vkino_room_chat_bet_variant_bet_variant_length
            check (char_length(bet_variant) > 0 and char_length(bet_variant) <= 5000),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger vkino_room_chat_bet_variant_set_updated_at
before update on vkino_room_chat_bet_variant
for each row execute function set_updated_at();


-- Ответ пользователя на ставку в чате комнаты совместного просмотра
create table if not exists vkino_room_chat_bet_answer (
    id bigint generated by default as identity primary key,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    bet_variant_id bigint not null
        references vkino_room_chat_bet_variant (id)
            on update cascade
            on delete cascade,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint vkino_room_chat_bet_answer_user_variant_unique
        unique (user_id, bet_variant_id)
);

create trigger vkino_room_chat_bet_answer_set_updated_at
before update on vkino_room_chat_bet_answer
for each row execute function set_updated_at();


-- Тариф
create table if not exists subscription_tariff (
    id bigint generated by default as identity primary key,

    title text not null
        constraint subscription_tariff_title_length_check
            check (char_length(trim(title)) > 0 and char_length(title) <= 255),

    description text,

    -- Цена в vkino_coins
    price_vkino_coins int not null default 0
        constraint subscription_tariff_price_vkino_coins_check
            check (price_vkino_coins >= 0),

    is_coins_payment_available boolean not null default false,

    -- Цена в рублях
    price_money int not null default 0
        constraint subscription_tariff_price_money_check
            check (price_money >= 0),

    is_money_payment_available boolean not null default true,

    duration_days int not null
        constraint subscription_tariff_duration_days_check
            check (duration_days > 0),

    is_active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint subscription_tariff_payment_available_check
        check (is_coins_payment_available = true or is_money_payment_available = true),

    constraint subscription_tariff_coins_price_required_check
        check (is_coins_payment_available = false or price_vkino_coins > 0),

    constraint subscription_tariff_money_price_required_check
        check (is_money_payment_available = false or price_money > 0)
);

create trigger subscription_tariff_set_updated_at
before update on subscription_tariff
for each row execute function set_updated_at();


-- Опция подписки
create table if not exists subscription_option (
    id bigint generated by default as identity primary key,

    code text not null
        constraint subscription_option_code_length_check
            check (char_length(trim(code)) > 0 and char_length(code) <= 100),

    title text not null
        constraint subscription_option_title_length_check
            check (char_length(trim(title)) > 0 and char_length(title) <= 255),

    description text,

    is_active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint subscription_option_code_unique
        unique (code)
);

create trigger subscription_option_set_updated_at
before update on subscription_option
for each row execute function set_updated_at();


-- Связь M2M
create table if not exists subscription_tariff_option (
    id bigint generated by default as identity primary key,

    subscription_tariff_id bigint not null
        references subscription_tariff (id)
            on update cascade
            on delete cascade,

    subscription_option_id bigint not null
        references subscription_option (id)
            on update cascade
            on delete restrict,

    created_at timestamptz not null default now(),

    constraint subscription_tariff_option_unique
        unique (subscription_tariff_id, subscription_option_id)
);


-- Подписка пользователя
create table if not exists user_subscription (
    id bigint generated by default as identity primary key,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    subscription_tariff_id bigint not null
        references subscription_tariff (id)
            on update cascade
            on delete restrict,

    starts_at timestamptz not null default now(),

    expires_at timestamptz not null,

    is_active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint user_subscription_expires_at_check
        check (expires_at > starts_at)
);

create trigger user_subscription_set_updated_at
before update on user_subscription
for each row execute function set_updated_at();


COMMIT;