BEGIN;

-- 00006 уже создает базовую room-схему:
-- vkino_room, vkino_room_chat_message, vkino_room_chat_bet,
-- vkino_room_chat_bet_variant, vkino_room_chat_bet_answer.
-- Здесь добавляем только то, чего там нет:
-- метаданные комнаты, membership, invite и playback snapshot.

alter table vkino_room
    add column if not exists name text not null default 'Watch Party',
    add column if not exists visibility text not null default 'private';

create table if not exists vkino_room_member (
    id bigint generated by default as identity primary key,

    vkino_room_id bigint not null
        references vkino_room (id)
            on update cascade
            on delete cascade,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    role text not null default 'member',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint vkino_room_member_room_user_unique
        unique (vkino_room_id, user_id)
);

create trigger vkino_room_member_set_updated_at
before update on vkino_room_member
for each row execute function set_updated_at();

create table if not exists vkino_room_invite (
    id bigint generated by default as identity primary key,

    vkino_room_id bigint not null
        references vkino_room (id)
            on update cascade
            on delete cascade,

    created_by_user_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    invite_code text not null,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    expires_at timestamptz null,

    constraint vkino_room_invite_code_unique
        unique (invite_code)
);

create trigger vkino_room_invite_set_updated_at
before update on vkino_room_invite
for each row execute function set_updated_at();

create table if not exists vkino_room_playback_state (
    id bigint generated by default as identity primary key,

    vkino_room_id bigint not null
        references vkino_room (id)
            on update cascade
            on delete cascade,

    movie_id bigint null
        references movie (id)
            on update cascade
            on delete set null,

    episode_id bigint null
        references episode (id)
            on update cascade
            on delete set null,

    playback_url text not null default '',
    duration_seconds bigint not null default 0,
    position_seconds bigint not null default 0,
    status text not null default 'paused',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint vkino_room_playback_state_room_unique
        unique (vkino_room_id)
);

create trigger vkino_room_playback_state_set_updated_at
before update on vkino_room_playback_state
for each row execute function set_updated_at();

insert into vkino_room_member (vkino_room_id, user_id, role)
select vr.id, vr.user_owner_id, 'host'
from vkino_room vr
on conflict (vkino_room_id, user_id) do nothing;

COMMIT;
