BEGIN;

ALTER TABLE payment
    ALTER COLUMN paid_at DROP NOT NULL,
    ALTER COLUMN paid_at DROP DEFAULT;

ALTER TABLE payment
    ADD COLUMN IF NOT EXISTS product_type text,
    ADD COLUMN IF NOT EXISTS product_ref_id bigint,
    ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS yookassa_payment_id text,
    ADD COLUMN IF NOT EXISTS idempotency_key text,
    ADD COLUMN IF NOT EXISTS confirmation_url text,
    ADD COLUMN IF NOT EXISTS metadata jsonb;

UPDATE payment
SET
    product_type = COALESCE(product_type, 'unknown'),
    status = 'succeeded'
WHERE product_type IS NULL;

ALTER TABLE payment
    ALTER COLUMN product_type SET NOT NULL;

ALTER TABLE payment
    ADD CONSTRAINT payment_product_type_check
        CHECK (product_type IN ('subscription', 'coins', 'paid_content', 'unknown')),
    ADD CONSTRAINT payment_status_check
        CHECK (status IN ('pending', 'succeeded', 'canceled')),
    ADD CONSTRAINT payment_yookassa_payment_id_unique
        UNIQUE (yookassa_payment_id),
    ADD CONSTRAINT payment_idempotency_key_unique
        UNIQUE (idempotency_key);

CREATE INDEX IF NOT EXISTS payment_user_id_status_idx
    ON payment (user_id, status);

CREATE INDEX IF NOT EXISTS payment_product_type_ref_idx
    ON payment (product_type, product_ref_id);

CREATE TABLE IF NOT EXISTS payment_webhook_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yookassa_payment_id text NOT NULL,
    event text NOT NULL,
    payload_hash text NOT NULL,
    processed_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT payment_webhook_event_unique
        UNIQUE (yookassa_payment_id, event)
);

COMMIT;
