BEGIN;

-- История начисления Vkino coins
create table if not exists vkino_coins_history (
    id bigint generated by default as identity primary key,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    vkino_coins_count int not null
        constraint vkino_coins_history_vkino_coins_count_check
            check (vkino_coins_count > 0),

    -- ежедневная, выигрыш, проигрыш, покупка
    operation_type text not null default 'daily'
        constraint vkino_coins_history_operation_type_check
            check (operation_type in ('daily', 'bet_win', 'bet_lose', 'purchase')),

    description text null
        constraint vkino_coins_history_description_length
            check (description is null or char_length(description) <= 4096),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger vkino_coins_history_set_updated_at
before update on vkino_coins_history
for each row execute function set_updated_at();


-- Комната совместного просмотра
create table if not exists vkino_room (
    id bigint generated by default as identity primary key,

    -- создатель комнаты
    user_creator_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    -- текущий владелец комнаты
    user_owner_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger vkino_room_set_updated_at
before update on vkino_room
for each row execute function set_updated_at();


-- Сообщения в чате комнаты совместного просмотра
create table if not exists vkino_room_chat_message (
    id bigint generated by default as identity primary key,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    vkino_room_id bigint not null
        references vkino_room (id)
            on update cascade
            on delete cascade,

    content text null
        constraint vkino_room_chat_message_content_length
            check (content is null or (char_length(content) > 0 and char_length(content) <= 5000)),

    content_file_key text null
        constraint vkino_room_chat_message_content_file_key_length
            check (content_file_key is null or (char_length(content_file_key) > 0 and char_length(content_file_key) <= 1024)),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint vkino_room_chat_message_content_or_file_check
        check (content is not null or content_file_key is not null)
);

create trigger vkino_room_chat_message_set_updated_at
before update on vkino_room_chat_message
for each row execute function set_updated_at();


-- Ставки в чате комнаты совместного просмотра
create table if not exists vkino_room_chat_bet (
    id bigint generated by default as identity primary key,

    user_creator_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    vkino_room_id bigint not null
        references vkino_room (id)
            on update cascade
            on delete cascade,

    vkino_coins_count int not null
        constraint vkino_room_chat_bet_vkino_coins_count_check
            check (vkino_coins_count > 0),

    bet_title text not null
    constraint vkino_room_chat_bet_bet_title_length
        check (char_length(bet_title) > 0 and char_length(bet_title) <= 5000),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger vkino_room_chat_bet_set_updated_at
before update on vkino_room_chat_bet
for each row execute function set_updated_at();


-- Вариант ответа на ставке в чате комнаты совместного просмотра
create table if not exists vkino_room_chat_bet_variant (
    id bigint generated by default as identity primary key,

    vkino_room_chat_bet_id bigint not null
        references vkino_room_chat_bet (id)
            on update cascade
            on delete cascade,

    bet_variant text not null
        constraint vkino_room_chat_bet_variant_bet_variant_length
            check (char_length(bet_variant) > 0 and char_length(bet_variant) <= 5000),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger vkino_room_chat_bet_variant_set_updated_at
before update on vkino_room_chat_bet_variant
for each row execute function set_updated_at();


-- Ответ пользователя на ставку в чате комнаты совместного просмотра
create table if not exists vkino_room_chat_bet_answer (
    id bigint generated by default as identity primary key,

    user_id bigint not null
        references users (id)
            on update cascade
            on delete restrict,

    bet_variant_id bigint not null
        references vkino_room_chat_bet_variant (id)
            on update cascade
            on delete cascade,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint vkino_room_chat_bet_answer_user_variant_unique
        unique (user_id, bet_variant_id)
);

create trigger vkino_room_chat_bet_answer_set_updated_at
before update on vkino_room_chat_bet_answer
for each row execute function set_updated_at();


-- Уровень подписки
create table if not exists subscription_level (
    id bigint generated by default as identity primary key,

    title text null
        constraint subscription_level_title_length
            check (title is null or char_length(title) <= 4096),

    description text null
        constraint subscription_level_description_length
            check (description is null or char_length(description) <= 4096),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger subscription_level_set_updated_at
before update on subscription_level
for each row execute function set_updated_at();


-- Возможности подписки
create table if not exists subscription_permission (
    id bigint generated by default as identity primary key,

    subscription_level_id bigint not null
        references subscription_level (id)
            on update cascade
            on delete restrict,

    permission text not null
        constraint subscription_permission_permission_length
            check (char_length(permission) > 0 and char_length(permission) <= 4096),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger subscription_permission_set_updated_at
before update on subscription_permission
for each row execute function set_updated_at();


COMMIT;