-- ======================================================================

-- Update_helper
create function set_updated_at() returns trigger as $$
begin
    new.updated_at := now();
    return new;
end;
$$ language plpgsql;

-- ======================================================================

-- Жанр
create table if not exists genre (
    id int generated by default as identity primary key,
	
    title text not null
        constraint genre_title_length
            check (char_length(title) > 0 and char_length(title) <= 256),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint genre_title_unique unique (title)
);

create trigger genre_set_updated_at
before update on genre
for each row execute function set_updated_at();


-- Язык
create table if not exists language (
    id int generated by default as identity primary key,
	
    title text not null
        constraint language_title_length
            check (char_length(title) > 0 and char_length(title) <= 128),
	
    description text null
        constraint language_description_length
            check (description is null or char_length(description) <= 2048),

    constraint language_title_unique unique (title)
);

-- можно добавить озвучку (отдельно) + внешний ключ на студию озвучки

-- Страна
create table if not exists country (
    id int generated by default as identity primary key,
	
    title text not null
        constraint country_title_length
            check (char_length(title) > 0 and char_length(title) <= 128),

    constraint country_title_unique unique (title)
);

-- Фильм (собирательная обложка)
create table if not exists movie (
    id int generated by default as identity primary key,

    title text not null
        constraint movie_title_length
            check (char_length(title) > 0 and char_length(title) <= 255),

    description text null
        constraint movie_description_length
            check (description is null or char_length(description) <= 4096),
	
	content_type text not null default 'film'
        constraint movie_content_type_check
            check (content_type in ('film', 'series')),

    release_year int not null
        constraint movie_release_year_check
            check (release_year >= 1888 and release_year <= 2100),

    duration_seconds int not null
        constraint movie_duration_check
            check (duration_seconds > 0),

    age_limit int not null default 0
        constraint movie_age_limit_check
            check (age_limit in (0, 6, 12, 14, 16, 18, 21)),

    original_language_id int not null
        references language (id)
            on update cascade
            on delete restrict,

    country_id int not null
        references country (id)
            on update cascade
            on delete restrict,

    -- ключ в S3 хранилище
    picture_file_key text not null
        constraint movie_picture_file_key_length
            check (char_length(picture_file_key) > 0 and char_length(picture_file_key) <= 1024),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint movie_picture_file_key_unique unique (picture_file_key)
);

create trigger movie_set_updated_at
before update on movie
for each row execute function set_updated_at();


-- Серия / эпизод
create table if not exists episode (
    id int generated by default as identity primary key,

    movie_id int not null
        references movie (id)
            on update cascade
            on delete cascade,

    description text null
        constraint episode_description_length
            check (description is null or char_length(description) <= 4096),
	
    season_number int not null
        constraint episode_season_number_check
            check (season_number > -1),

    episode_number int not null
        constraint episode_episode_number_check
            check (episode_number > 0),

    title text null
        constraint episode_title_length
            check (title is null or (char_length(title) > 0 and char_length(title) <= 255)),

    duration_seconds int not null
        constraint episode_duration_check
            check (duration_seconds > 0),

	-- ключи в S3 хранилище
    picture_file_key text not null
        constraint movie_picture_file_key_length
            check (char_length(picture_file_key) > 0 and char_length(picture_file_key) <= 1024),

    video_file_key text not null
        constraint episode_video_file_key_length
            check (char_length(video_file_key) > 0 and char_length(video_file_key) <= 1024),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint episode_unique_in_series unique (movie_id, season_number, episode_number),
    constraint episode_picture_file_key_unique unique (picture_file_key),
    constraint episode_video_file_key_unique unique (video_file_key)
);

create trigger episode_set_updated_at
before update on episode
for each row execute function set_updated_at();


-- Актёр
create table if not exists actor (
    id int generated by default as identity primary key,

    full_name text not null
        constraint actor_name_length
            check (char_length(full_name) > 0 and char_length(full_name) <= 512),

    birthday date null,
	
    biography text null
        constraint actor_biography_length
            check (biography is null or char_length(biography) <= 2000),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
	
	constraint actor_full_name_birthday_unique unique (full_name, birthday)
);

create trigger actor_set_updated_at
before update on actor
for each row execute function set_updated_at();


-- Таблица связи фильма и жанра
create table if not exists genre_to_movie (
    id int generated by default as identity primary key,

    genre_id int not null
        references genre (id)
            on update cascade
            on delete restrict,

    movie_id int not null
        references movie (id)
            on update cascade
            on delete cascade,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint genre_to_movie_unique unique (genre_id, movie_id)
);

create trigger genre_to_movie_set_updated_at
before update on genre_to_movie
for each row execute function set_updated_at();


-- Актёры в фильме
create table if not exists actor_to_movie (
    id int generated by default as identity primary key,

    actor_id int not null
        references actor (id)
            on update cascade
            on delete restrict,

    movie_id int not null
        references movie (id)
            on update cascade
            on delete cascade,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint actor_to_movie_unique unique (actor_id, movie_id)
);

create trigger actor_to_movie_set_updated_at
before update on actor_to_movie
for each row execute function set_updated_at();


-- Подборки
create table if not exists selection (
    id int generated by default as identity primary key,

    title text not null
        constraint selection_title_length
            check (char_length(title) > 0 and char_length(title) <= 255),
	
    emotion text null
        constraint selection_emotion_length
            check (emotion is null or char_length(emotion) <= 128),

    rating numeric(4, 2) null
        constraint selection_rating_check
            check (rating is null or (rating >= 0 and rating <= 10)),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint selection_title_unique unique (title)
);

create trigger selection_set_updated_at
before update on selection
for each row execute function set_updated_at();


-- Фильмы в подборке
create table if not exists movie_to_selection (
    id int generated by default as identity primary key,

    movie_id int not null
        references movie (id)
            on update cascade
            on delete cascade,

    selection_id int not null
        references selection (id)
            on update cascade
            on delete cascade,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint movie_to_selection_unique unique (movie_id, selection_id)
);

create trigger movie_to_selection_set_updated_at
before update on movie_to_selection
for each row execute function set_updated_at();


-- Аккаунт пользователя
create table if not exists users (
    id int generated by default as identity primary key,

    email text not null
        constraint user_email_length
            check (char_length(email) >= 3 and char_length(email) <= 64),

    password_hash text not null
        constraint user_password_hash_length
            check (char_length(password_hash) >= 20 and char_length(password_hash) <= 255),

    registration_date timestamptz not null default now(),
    is_active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
	
	constraint user_email_unique unique (email)
);

create trigger user_set_updated_at
before update on users
for each row execute function set_updated_at();


-- Отзывы пользователя
create table if not exists user_interaction (
    id int generated by default as identity primary key,

    movie_id int not null
        references movie (id)
            on update cascade
            on delete cascade,

    user_id int not null
        references users (id)
            on update cascade
            on delete cascade,

    rating numeric(4, 2) null
        constraint user_interaction_rating_check
            check (rating is null or (rating >= 0 and rating <= 10)),

    is_favorite boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint user_interaction_unique unique (movie_id, user_id)
);

create trigger user_interaction_set_updated_at
before update on user_interaction
for each row execute function set_updated_at();


-- История просмотра
create table if not exists watch_progress_episode (
	id int generated by default as identity primary key,
    user_id int not null
        references users (id)
            on update cascade
            on delete cascade,

    episode_id int not null
        references episode (id)
            on update cascade
            on delete cascade,

    position_seconds int not null
        constraint watch_progress_episode_position_check
            check (position_seconds >= 0),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

	constraint user_episode_unique unique (user_id, episode_id)
);

create trigger watch_progress_episode_set_updated_at
before update on watch_progress_episode
for each row execute function set_updated_at();


-- Друзья
create table if not exists friend (
    id int generated by default as identity primary key,

    user1_id int not null
        references users (id)
            on update cascade
            on delete cascade,
	
	user2_id int not null
        references users (id)
            on update cascade
            on delete cascade,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
	
	constraint friend_not_self_check check (user1_id <> user2_id),
    constraint friend_order_check check (user1_id < user2_id),
    constraint friend_unique unique (user1_id, user2_id)
);

create trigger friend_set_updated_at
before update on friend
for each row execute function set_updated_at();


-- Оплата
create table if not exists payment (
    id int generated by default as identity primary key,

    user_id int not null
        references users (id)
            on update cascade
            on delete cascade,

    amount numeric(12, 2) not null
        constraint payment_amount_check
            check (amount > 0),

    currency text not null default 'RUB'
        constraint payment_currency_length
            check (char_length(currency) = 3),

    paid_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger payment_set_updated_at
before update on payment
for each row execute function set_updated_at();


-- Сессии
create table if not exists user_session (
    id int generated by default as identity primary key,

    user_id int not null
        references users (id)
            on update cascade
            on delete cascade,

    refresh_token text not null
        constraint refresh_session_token_length
            check (char_length(refresh_token) >= 32 and char_length(refresh_token) <= 512),

    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint user_id_unique unique (user_id)
);

create trigger user_session_set_updated_at
before update on user_session
for each row execute function set_updated_at();


-- Добавить совместные комнаты просмотра