// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/payment-service/repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=./internal/app/payment-service/repository/interface.go -destination=./internal/app/payment-service/repository/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/go-park-mail-ru/2026_1_VKino/internal/app/payment-service/domain"
	repository "github.com/go-park-mail-ru/2026_1_VKino/internal/app/payment-service/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepo is a mock of PaymentRepo interface.
type MockPaymentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepoMockRecorder
	isgomock struct{}
}

// MockPaymentRepoMockRecorder is the mock recorder for MockPaymentRepo.
type MockPaymentRepoMockRecorder struct {
	mock *MockPaymentRepo
}

// NewMockPaymentRepo creates a new mock instance.
func NewMockPaymentRepo(ctrl *gomock.Controller) *MockPaymentRepo {
	mock := &MockPaymentRepo{ctrl: ctrl}
	mock.recorder = &MockPaymentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepo) EXPECT() *MockPaymentRepoMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentRepo) CreatePayment(ctx context.Context, payment domain.Payment) (domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, payment)
	ret0, _ := ret[0].(domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentRepoMockRecorder) CreatePayment(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentRepo)(nil).CreatePayment), ctx, payment)
}

// GetPaymentByID mocks base method.
func (m *MockPaymentRepo) GetPaymentByID(ctx context.Context, paymentID int64) (domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByID", ctx, paymentID)
	ret0, _ := ret[0].(domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByID indicates an expected call of GetPaymentByID.
func (mr *MockPaymentRepoMockRecorder) GetPaymentByID(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByID", reflect.TypeOf((*MockPaymentRepo)(nil).GetPaymentByID), ctx, paymentID)
}

// GetPaymentByYooKassaID mocks base method.
func (m *MockPaymentRepo) GetPaymentByYooKassaID(ctx context.Context, yookassaPaymentID string) (domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByYooKassaID", ctx, yookassaPaymentID)
	ret0, _ := ret[0].(domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByYooKassaID indicates an expected call of GetPaymentByYooKassaID.
func (mr *MockPaymentRepoMockRecorder) GetPaymentByYooKassaID(ctx, yookassaPaymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByYooKassaID", reflect.TypeOf((*MockPaymentRepo)(nil).GetPaymentByYooKassaID), ctx, yookassaPaymentID)
}

// GetSubscriptionTariff mocks base method.
func (m *MockPaymentRepo) GetSubscriptionTariff(ctx context.Context, tariffID int64) (domain.SubscriptionTariff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionTariff", ctx, tariffID)
	ret0, _ := ret[0].(domain.SubscriptionTariff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionTariff indicates an expected call of GetSubscriptionTariff.
func (mr *MockPaymentRepoMockRecorder) GetSubscriptionTariff(ctx, tariffID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionTariff", reflect.TypeOf((*MockPaymentRepo)(nil).GetSubscriptionTariff), ctx, tariffID)
}

// ListMoneyTariffs mocks base method.
func (m *MockPaymentRepo) ListMoneyTariffs(ctx context.Context) ([]domain.MoneyTariff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMoneyTariffs", ctx)
	ret0, _ := ret[0].([]domain.MoneyTariff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMoneyTariffs indicates an expected call of ListMoneyTariffs.
func (mr *MockPaymentRepoMockRecorder) ListMoneyTariffs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMoneyTariffs", reflect.TypeOf((*MockPaymentRepo)(nil).ListMoneyTariffs), ctx)
}

// TryRegisterWebhookEvent mocks base method.
func (m *MockPaymentRepo) TryRegisterWebhookEvent(ctx context.Context, yookassaPaymentID, event, payloadHash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryRegisterWebhookEvent", ctx, yookassaPaymentID, event, payloadHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryRegisterWebhookEvent indicates an expected call of TryRegisterWebhookEvent.
func (mr *MockPaymentRepoMockRecorder) TryRegisterWebhookEvent(ctx, yookassaPaymentID, event, payloadHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryRegisterWebhookEvent", reflect.TypeOf((*MockPaymentRepo)(nil).TryRegisterWebhookEvent), ctx, yookassaPaymentID, event, payloadHash)
}

// UpdatePaymentStatus mocks base method.
func (m *MockPaymentRepo) UpdatePaymentStatus(ctx context.Context, paymentID int64, status domain.PaymentStatus, paidAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatus", ctx, paymentID, status, paidAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentStatus indicates an expected call of UpdatePaymentStatus.
func (mr *MockPaymentRepoMockRecorder) UpdatePaymentStatus(ctx, paymentID, status, paidAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatus", reflect.TypeOf((*MockPaymentRepo)(nil).UpdatePaymentStatus), ctx, paymentID, status, paidAt)
}

// UpdatePaymentYooKassa mocks base method.
func (m *MockPaymentRepo) UpdatePaymentYooKassa(ctx context.Context, paymentID int64, yookassaPaymentID, confirmationURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentYooKassa", ctx, paymentID, yookassaPaymentID, confirmationURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentYooKassa indicates an expected call of UpdatePaymentYooKassa.
func (mr *MockPaymentRepoMockRecorder) UpdatePaymentYooKassa(ctx, paymentID, yookassaPaymentID, confirmationURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentYooKassa", reflect.TypeOf((*MockPaymentRepo)(nil).UpdatePaymentYooKassa), ctx, paymentID, yookassaPaymentID, confirmationURL)
}

// UserExists mocks base method.
func (m *MockPaymentRepo) UserExists(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserExists", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserExists indicates an expected call of UserExists.
func (mr *MockPaymentRepoMockRecorder) UserExists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserExists", reflect.TypeOf((*MockPaymentRepo)(nil).UserExists), ctx, userID)
}

// MockYooKassaClient is a mock of YooKassaClient interface.
type MockYooKassaClient struct {
	ctrl     *gomock.Controller
	recorder *MockYooKassaClientMockRecorder
	isgomock struct{}
}

// MockYooKassaClientMockRecorder is the mock recorder for MockYooKassaClient.
type MockYooKassaClientMockRecorder struct {
	mock *MockYooKassaClient
}

// NewMockYooKassaClient creates a new mock instance.
func NewMockYooKassaClient(ctrl *gomock.Controller) *MockYooKassaClient {
	mock := &MockYooKassaClient{ctrl: ctrl}
	mock.recorder = &MockYooKassaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYooKassaClient) EXPECT() *MockYooKassaClientMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockYooKassaClient) CreatePayment(ctx context.Context, req repository.YooKassaCreateRequest) (repository.YooKassaPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, req)
	ret0, _ := ret[0].(repository.YooKassaPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockYooKassaClientMockRecorder) CreatePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockYooKassaClient)(nil).CreatePayment), ctx, req)
}

// GetPayment mocks base method.
func (m *MockYooKassaClient) GetPayment(ctx context.Context, paymentID string) (repository.YooKassaPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayment", ctx, paymentID)
	ret0, _ := ret[0].(repository.YooKassaPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockYooKassaClientMockRecorder) GetPayment(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockYooKassaClient)(nil).GetPayment), ctx, paymentID)
}

// MockSubscriptionActivator is a mock of SubscriptionActivator interface.
type MockSubscriptionActivator struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionActivatorMockRecorder
	isgomock struct{}
}

// MockSubscriptionActivatorMockRecorder is the mock recorder for MockSubscriptionActivator.
type MockSubscriptionActivatorMockRecorder struct {
	mock *MockSubscriptionActivator
}

// NewMockSubscriptionActivator creates a new mock instance.
func NewMockSubscriptionActivator(ctrl *gomock.Controller) *MockSubscriptionActivator {
	mock := &MockSubscriptionActivator{ctrl: ctrl}
	mock.recorder = &MockSubscriptionActivatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionActivator) EXPECT() *MockSubscriptionActivatorMockRecorder {
	return m.recorder
}

// ActivateSubscription mocks base method.
func (m *MockSubscriptionActivator) ActivateSubscription(ctx context.Context, userID, tariffID, paymentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateSubscription", ctx, userID, tariffID, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateSubscription indicates an expected call of ActivateSubscription.
func (mr *MockSubscriptionActivatorMockRecorder) ActivateSubscription(ctx, userID, tariffID, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateSubscription", reflect.TypeOf((*MockSubscriptionActivator)(nil).ActivateSubscription), ctx, userID, tariffID, paymentID)
}

// MockSubscriptionCoinsBuyer is a mock of SubscriptionCoinsBuyer interface.
type MockSubscriptionCoinsBuyer struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionCoinsBuyerMockRecorder
	isgomock struct{}
}

// MockSubscriptionCoinsBuyerMockRecorder is the mock recorder for MockSubscriptionCoinsBuyer.
type MockSubscriptionCoinsBuyerMockRecorder struct {
	mock *MockSubscriptionCoinsBuyer
}

// NewMockSubscriptionCoinsBuyer creates a new mock instance.
func NewMockSubscriptionCoinsBuyer(ctrl *gomock.Controller) *MockSubscriptionCoinsBuyer {
	mock := &MockSubscriptionCoinsBuyer{ctrl: ctrl}
	mock.recorder = &MockSubscriptionCoinsBuyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionCoinsBuyer) EXPECT() *MockSubscriptionCoinsBuyerMockRecorder {
	return m.recorder
}

// BuySubscriptionWithVKinoCoins mocks base method.
func (m *MockSubscriptionCoinsBuyer) BuySubscriptionWithVKinoCoins(ctx context.Context, userID, tariffID int64) (domain.CoinsSubscriptionPurchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuySubscriptionWithVKinoCoins", ctx, userID, tariffID)
	ret0, _ := ret[0].(domain.CoinsSubscriptionPurchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuySubscriptionWithVKinoCoins indicates an expected call of BuySubscriptionWithVKinoCoins.
func (mr *MockSubscriptionCoinsBuyerMockRecorder) BuySubscriptionWithVKinoCoins(ctx, userID, tariffID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuySubscriptionWithVKinoCoins", reflect.TypeOf((*MockSubscriptionCoinsBuyer)(nil).BuySubscriptionWithVKinoCoins), ctx, userID, tariffID)
}
