services:
  nginx:
    image: nginx:latest
    container_name: front-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    extra_hosts:
      - host.docker.internal:host-gateway

  vkino-api-dev:
    build:
      context: ../..
      dockerfile: build/image/Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../../configs/api.yaml:/etc/vkino/config.yaml
    command: ./vkinoapi --config=/etc/vkino/config.yaml
    
