services:
  nginx:
    image: nginx:trixie-perl
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    extra_hosts:
      - host.docker.internal:host-gateway

  api-gateway:
    build:
      context: ../..
      dockerfile: build/image/Dockerfile
      args:
        SERVICE_PATH: services/api-gateway/cmd/gateway
        BINARY_NAME: gateway
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ../../services/api-gateway/configs/config.yaml:/etc/vkino/config.yaml:ro
      - ./logs/app:/vkinoapi/logs/app
    command: ./gateway -config /etc/vkino/config.yaml

  auth-service:
    env_file:
      - ./.env
    build:
      context: ../..
      dockerfile: build/image/Dockerfile
      args:
        SERVICE_PATH: services/auth/cmd/auth
        BINARY_NAME: auth
    restart: always
    volumes:
      - ../../services/auth/configs/config.yaml:/etc/vkino/config.yaml:ro
      - ./logs/app:/vkinoapi/logs/app
    command: ./auth -config /etc/vkino/config.yaml
    expose:
      - "9090"

  user-service:
    env_file:
      - ./.env
    build:
      context: ../..
      dockerfile: build/image/Dockerfile
      args:
        SERVICE_PATH: services/user/cmd/user
        BINARY_NAME: user
    restart: always
    volumes:
      - ../../services/user/configs/config.yaml:/etc/vkino/config.yaml:ro
      - ./logs/app:/vkinoapi/logs/app
    command: ./user -config /etc/vkino/config.yaml
    expose:
      - "9091"

  movie-service:
    env_file:
      - ./.env
    build:
      context: ../..
      dockerfile: build/image/Dockerfile
      args:
        SERVICE_PATH: services/movie/cmd/movie
        BINARY_NAME: movie
    restart: always
    volumes:
      - ../../services/movie/configs/config.yaml:/etc/vkino/config.yaml:ro
      - ./logs/app:/vkinoapi/logs/app
    command: ./movie -config /etc/vkino/config.yaml
    expose:
      - "9092"

  db:
    image: postgres:18.3
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 5434:5432
    volumes:
      - db-data:/var/lib/postgresql

  migrate:
    image: migrate/migrate
    env_file:
      - ./.env
    volumes:
      - ../../migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable",
        "up"
      ]
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  minio:
    image: minio/minio:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    env_file:
      - ./.env
    depends_on:
      - minio
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; do
        echo 'waiting for minio...';
        sleep 2;
      done;
      /usr/bin/mc mb -p local/vkino-actors || true;
      /usr/bin/mc mb -p local/vkino-posters || true;
      /usr/bin/mc mb -p local/vkino-cards || true;
      /usr/bin/mc mb -p local/vkino-avatars || true;
      /usr/bin/mc mb -p local/vkino-videos || true;
      /usr/bin/mc anonymous set none local/vkino-actors || true;
      /usr/bin/mc anonymous set none local/vkino-posters || true;
      /usr/bin/mc anonymous set none local/vkino-cards || true;
      /usr/bin/mc anonymous set none local/vkino-avatars || true;
      /usr/bin/mc anonymous set none local/vkino-videos || true;
      exit 0;
      "

volumes:
  db-data:
  minio_data:
