services:
  vkino-api-dev:
    build:
      context: ../..
      dockerfile: build/image/Dockerfile
    container_name: vkino-back
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../../configs/api.yaml:/etc/vkino/config.yaml
    command: ./vkinoapi --config=/etc/vkino/config.yaml
    networks:
      - vkino-network

  nginx:
    image: nginx:latest
    container_name: vkino-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - vkino-api-dev
    networks:
      - vkino-network

networks:
  vkino-network:
    driver: bridge