server:
  port: 8080
  timeouts:
    read_header: "5s"
    read: "10s"
    write: "15s"
    idle: "60s"

logger:
  level: "debug"
  format: "text"
  output_path: "logs/app/vkinoapi.log"

postgres:
  host: "db"                    
  port: 5432
  user: "vkino_user"            
  password: "vkino"            
  dbname: "vkino"              
  sslmode: "disable"
  max_pool_size: 25
  conn_attempts: 10
  conn_timeout: "5s"
  
auth:
  jwt_secret: "dev-secret"
  access_token_ttl: "15m"
  refresh_token_ttl: "336h"         # 14 дней
  refresh_cookie_name: "refresh_token"
  cookie_secure: false              # для localhost false

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "https://vkino.tech"
    - "https://www.vkino.tech"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization
  allow_credentials: true
  max_age: 3600

s3:
  internal_endpoint: "minio:9000"
  public_endpoint: "localhost:9000"
  region: "us-east-1"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  bucket_images: "vkino-images"
  bucket_avatars: "vkino-avatars"
  bucket_videos: "vkino-videos"
  internal_use_ssl: false
  public_use_ssl: false
  use_path_style: true
  presign_ttl: "15m"
