// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination=./mocks/user_repo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/go-park-mail-ru/2026_1_VKino/internal/app/user-service/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserReadRepo is a mock of UserReadRepo interface.
type MockUserReadRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserReadRepoMockRecorder
	isgomock struct{}
}

// MockUserReadRepoMockRecorder is the mock recorder for MockUserReadRepo.
type MockUserReadRepoMockRecorder struct {
	mock *MockUserReadRepo
}

// NewMockUserReadRepo creates a new mock instance.
func NewMockUserReadRepo(ctrl *gomock.Controller) *MockUserReadRepo {
	mock := &MockUserReadRepo{ctrl: ctrl}
	mock.recorder = &MockUserReadRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserReadRepo) EXPECT() *MockUserReadRepoMockRecorder {
	return m.recorder
}

// GetFriend mocks base method.
func (m *MockUserReadRepo) GetFriend(ctx context.Context, userID, friendID int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriend", ctx, userID, friendID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriend indicates an expected call of GetFriend.
func (mr *MockUserReadRepoMockRecorder) GetFriend(ctx, userID, friendID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriend", reflect.TypeOf((*MockUserReadRepo)(nil).GetFriend), ctx, userID, friendID)
}

// GetUserByEmail mocks base method.
func (m *MockUserReadRepo) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserReadRepoMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserReadRepo)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserReadRepo) GetUserByID(ctx context.Context, id int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserReadRepoMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserReadRepo)(nil).GetUserByID), ctx, id)
}

// GetUserRole mocks base method.
func (m *MockUserReadRepo) GetUserRole(ctx context.Context, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockUserReadRepoMockRecorder) GetUserRole(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockUserReadRepo)(nil).GetUserRole), ctx, userID)
}

// SearchUsersByEmail mocks base method.
func (m *MockUserReadRepo) SearchUsersByEmail(ctx context.Context, userID int64, query string) ([]domain.UserSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersByEmail", ctx, userID, query)
	ret0, _ := ret[0].([]domain.UserSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersByEmail indicates an expected call of SearchUsersByEmail.
func (mr *MockUserReadRepoMockRecorder) SearchUsersByEmail(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersByEmail", reflect.TypeOf((*MockUserReadRepo)(nil).SearchUsersByEmail), ctx, userID, query)
}

// MockUserProfileMutationRepo is a mock of UserProfileMutationRepo interface.
type MockUserProfileMutationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileMutationRepoMockRecorder
	isgomock struct{}
}

// MockUserProfileMutationRepoMockRecorder is the mock recorder for MockUserProfileMutationRepo.
type MockUserProfileMutationRepoMockRecorder struct {
	mock *MockUserProfileMutationRepo
}

// NewMockUserProfileMutationRepo creates a new mock instance.
func NewMockUserProfileMutationRepo(ctrl *gomock.Controller) *MockUserProfileMutationRepo {
	mock := &MockUserProfileMutationRepo{ctrl: ctrl}
	mock.recorder = &MockUserProfileMutationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileMutationRepo) EXPECT() *MockUserProfileMutationRepoMockRecorder {
	return m.recorder
}

// UpdateAvatarFileKey mocks base method.
func (m *MockUserProfileMutationRepo) UpdateAvatarFileKey(ctx context.Context, userID int64, avatarFileKey *string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatarFileKey", ctx, userID, avatarFileKey)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvatarFileKey indicates an expected call of UpdateAvatarFileKey.
func (mr *MockUserProfileMutationRepoMockRecorder) UpdateAvatarFileKey(ctx, userID, avatarFileKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatarFileKey", reflect.TypeOf((*MockUserProfileMutationRepo)(nil).UpdateAvatarFileKey), ctx, userID, avatarFileKey)
}

// UpdateBirthdate mocks base method.
func (m *MockUserProfileMutationRepo) UpdateBirthdate(ctx context.Context, userID int64, birthdate *time.Time) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBirthdate", ctx, userID, birthdate)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBirthdate indicates an expected call of UpdateBirthdate.
func (mr *MockUserProfileMutationRepoMockRecorder) UpdateBirthdate(ctx, userID, birthdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBirthdate", reflect.TypeOf((*MockUserProfileMutationRepo)(nil).UpdateBirthdate), ctx, userID, birthdate)
}

// MockUserSubscriptionRepo is a mock of UserSubscriptionRepo interface.
type MockUserSubscriptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserSubscriptionRepoMockRecorder
	isgomock struct{}
}

// MockUserSubscriptionRepoMockRecorder is the mock recorder for MockUserSubscriptionRepo.
type MockUserSubscriptionRepoMockRecorder struct {
	mock *MockUserSubscriptionRepo
}

// NewMockUserSubscriptionRepo creates a new mock instance.
func NewMockUserSubscriptionRepo(ctrl *gomock.Controller) *MockUserSubscriptionRepo {
	mock := &MockUserSubscriptionRepo{ctrl: ctrl}
	mock.recorder = &MockUserSubscriptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSubscriptionRepo) EXPECT() *MockUserSubscriptionRepoMockRecorder {
	return m.recorder
}

// CreateUserSubscription mocks base method.
func (m *MockUserSubscriptionRepo) CreateUserSubscription(ctx context.Context, userID, tariffID int64, startsAt, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserSubscription", ctx, userID, tariffID, startsAt, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserSubscription indicates an expected call of CreateUserSubscription.
func (mr *MockUserSubscriptionRepoMockRecorder) CreateUserSubscription(ctx, userID, tariffID, startsAt, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserSubscription", reflect.TypeOf((*MockUserSubscriptionRepo)(nil).CreateUserSubscription), ctx, userID, tariffID, startsAt, expiresAt)
}

// DeactivateUserSubscriptions mocks base method.
func (m *MockUserSubscriptionRepo) DeactivateUserSubscriptions(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUserSubscriptions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUserSubscriptions indicates an expected call of DeactivateUserSubscriptions.
func (mr *MockUserSubscriptionRepoMockRecorder) DeactivateUserSubscriptions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUserSubscriptions", reflect.TypeOf((*MockUserSubscriptionRepo)(nil).DeactivateUserSubscriptions), ctx, userID)
}

// GetActiveSubscription mocks base method.
func (m *MockUserSubscriptionRepo) GetActiveSubscription(ctx context.Context, userID int64) (domain.SubscriptionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSubscription", ctx, userID)
	ret0, _ := ret[0].(domain.SubscriptionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSubscription indicates an expected call of GetActiveSubscription.
func (mr *MockUserSubscriptionRepoMockRecorder) GetActiveSubscription(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSubscription", reflect.TypeOf((*MockUserSubscriptionRepo)(nil).GetActiveSubscription), ctx, userID)
}

// GetCoinsReceivedToday mocks base method.
func (m *MockUserSubscriptionRepo) GetCoinsReceivedToday(ctx context.Context, userID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinsReceivedToday", ctx, userID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinsReceivedToday indicates an expected call of GetCoinsReceivedToday.
func (mr *MockUserSubscriptionRepoMockRecorder) GetCoinsReceivedToday(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinsReceivedToday", reflect.TypeOf((*MockUserSubscriptionRepo)(nil).GetCoinsReceivedToday), ctx, userID)
}

// GetRoomsCreatedThisMonth mocks base method.
func (m *MockUserSubscriptionRepo) GetRoomsCreatedThisMonth(ctx context.Context, userID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomsCreatedThisMonth", ctx, userID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomsCreatedThisMonth indicates an expected call of GetRoomsCreatedThisMonth.
func (mr *MockUserSubscriptionRepoMockRecorder) GetRoomsCreatedThisMonth(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomsCreatedThisMonth", reflect.TypeOf((*MockUserSubscriptionRepo)(nil).GetRoomsCreatedThisMonth), ctx, userID)
}

// GetSubscriptionTariffByCode mocks base method.
func (m *MockUserSubscriptionRepo) GetSubscriptionTariffByCode(ctx context.Context, code string) (domain.SubscriptionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionTariffByCode", ctx, code)
	ret0, _ := ret[0].(domain.SubscriptionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionTariffByCode indicates an expected call of GetSubscriptionTariffByCode.
func (mr *MockUserSubscriptionRepoMockRecorder) GetSubscriptionTariffByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionTariffByCode", reflect.TypeOf((*MockUserSubscriptionRepo)(nil).GetSubscriptionTariffByCode), ctx, code)
}

// GetSubscriptionTariffByID mocks base method.
func (m *MockUserSubscriptionRepo) GetSubscriptionTariffByID(ctx context.Context, tariffID int64) (domain.SubscriptionTariff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionTariffByID", ctx, tariffID)
	ret0, _ := ret[0].(domain.SubscriptionTariff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionTariffByID indicates an expected call of GetSubscriptionTariffByID.
func (mr *MockUserSubscriptionRepoMockRecorder) GetSubscriptionTariffByID(ctx, tariffID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionTariffByID", reflect.TypeOf((*MockUserSubscriptionRepo)(nil).GetSubscriptionTariffByID), ctx, tariffID)
}

// GetSubscriptionTariffOptions mocks base method.
func (m *MockUserSubscriptionRepo) GetSubscriptionTariffOptions(ctx context.Context, tariffID int64) ([]domain.SubscriptionOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionTariffOptions", ctx, tariffID)
	ret0, _ := ret[0].([]domain.SubscriptionOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionTariffOptions indicates an expected call of GetSubscriptionTariffOptions.
func (mr *MockUserSubscriptionRepoMockRecorder) GetSubscriptionTariffOptions(ctx, tariffID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionTariffOptions", reflect.TypeOf((*MockUserSubscriptionRepo)(nil).GetSubscriptionTariffOptions), ctx, tariffID)
}

// MockUserMovieRepo is a mock of UserMovieRepo interface.
type MockUserMovieRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserMovieRepoMockRecorder
	isgomock struct{}
}

// MockUserMovieRepoMockRecorder is the mock recorder for MockUserMovieRepo.
type MockUserMovieRepoMockRecorder struct {
	mock *MockUserMovieRepo
}

// NewMockUserMovieRepo creates a new mock instance.
func NewMockUserMovieRepo(ctrl *gomock.Controller) *MockUserMovieRepo {
	mock := &MockUserMovieRepo{ctrl: ctrl}
	mock.recorder = &MockUserMovieRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserMovieRepo) EXPECT() *MockUserMovieRepoMockRecorder {
	return m.recorder
}

// AddMovieToFavorites mocks base method.
func (m *MockUserMovieRepo) AddMovieToFavorites(ctx context.Context, userID, movieID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMovieToFavorites", ctx, userID, movieID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMovieToFavorites indicates an expected call of AddMovieToFavorites.
func (mr *MockUserMovieRepoMockRecorder) AddMovieToFavorites(ctx, userID, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMovieToFavorites", reflect.TypeOf((*MockUserMovieRepo)(nil).AddMovieToFavorites), ctx, userID, movieID)
}

// DeleteMovieReview mocks base method.
func (m *MockUserMovieRepo) DeleteMovieReview(ctx context.Context, userID, movieID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMovieReview", ctx, userID, movieID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMovieReview indicates an expected call of DeleteMovieReview.
func (mr *MockUserMovieRepoMockRecorder) DeleteMovieReview(ctx, userID, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMovieReview", reflect.TypeOf((*MockUserMovieRepo)(nil).DeleteMovieReview), ctx, userID, movieID)
}

// DeleteReviewReaction mocks base method.
func (m *MockUserMovieRepo) DeleteReviewReaction(ctx context.Context, userID, reviewID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReviewReaction", ctx, userID, reviewID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReviewReaction indicates an expected call of DeleteReviewReaction.
func (mr *MockUserMovieRepoMockRecorder) DeleteReviewReaction(ctx, userID, reviewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReviewReaction", reflect.TypeOf((*MockUserMovieRepo)(nil).DeleteReviewReaction), ctx, userID, reviewID)
}

// GetFavorites mocks base method.
func (m *MockUserMovieRepo) GetFavorites(ctx context.Context, userID int64, limit, offset int32) ([]int64, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavorites", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFavorites indicates an expected call of GetFavorites.
func (mr *MockUserMovieRepoMockRecorder) GetFavorites(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavorites", reflect.TypeOf((*MockUserMovieRepo)(nil).GetFavorites), ctx, userID, limit, offset)
}

// SetMovieRating mocks base method.
func (m *MockUserMovieRepo) SetMovieRating(ctx context.Context, userID, movieID int64, rating float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMovieRating", ctx, userID, movieID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMovieRating indicates an expected call of SetMovieRating.
func (mr *MockUserMovieRepoMockRecorder) SetMovieRating(ctx, userID, movieID, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMovieRating", reflect.TypeOf((*MockUserMovieRepo)(nil).SetMovieRating), ctx, userID, movieID, rating)
}

// SetMovieReview mocks base method.
func (m *MockUserMovieRepo) SetMovieReview(ctx context.Context, userID, movieID int64, rating *float64, comment *string) (domain.MovieReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMovieReview", ctx, userID, movieID, rating, comment)
	ret0, _ := ret[0].(domain.MovieReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMovieReview indicates an expected call of SetMovieReview.
func (mr *MockUserMovieRepoMockRecorder) SetMovieReview(ctx, userID, movieID, rating, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMovieReview", reflect.TypeOf((*MockUserMovieRepo)(nil).SetMovieReview), ctx, userID, movieID, rating, comment)
}

// SetReviewReaction mocks base method.
func (m *MockUserMovieRepo) SetReviewReaction(ctx context.Context, userID, reviewID int64, reaction string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReviewReaction", ctx, userID, reviewID, reaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReviewReaction indicates an expected call of SetReviewReaction.
func (mr *MockUserMovieRepoMockRecorder) SetReviewReaction(ctx, userID, reviewID, reaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReviewReaction", reflect.TypeOf((*MockUserMovieRepo)(nil).SetReviewReaction), ctx, userID, reviewID, reaction)
}

// ToggleFavorite mocks base method.
func (m *MockUserMovieRepo) ToggleFavorite(ctx context.Context, userID, movieID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleFavorite", ctx, userID, movieID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleFavorite indicates an expected call of ToggleFavorite.
func (mr *MockUserMovieRepoMockRecorder) ToggleFavorite(ctx, userID, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleFavorite", reflect.TypeOf((*MockUserMovieRepo)(nil).ToggleFavorite), ctx, userID, movieID)
}

// MockUserFriendRepo is a mock of UserFriendRepo interface.
type MockUserFriendRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserFriendRepoMockRecorder
	isgomock struct{}
}

// MockUserFriendRepoMockRecorder is the mock recorder for MockUserFriendRepo.
type MockUserFriendRepoMockRecorder struct {
	mock *MockUserFriendRepo
}

// NewMockUserFriendRepo creates a new mock instance.
func NewMockUserFriendRepo(ctrl *gomock.Controller) *MockUserFriendRepo {
	mock := &MockUserFriendRepo{ctrl: ctrl}
	mock.recorder = &MockUserFriendRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFriendRepo) EXPECT() *MockUserFriendRepoMockRecorder {
	return m.recorder
}

// AddFriend mocks base method.
func (m *MockUserFriendRepo) AddFriend(ctx context.Context, userID, friendID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFriend", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFriend indicates an expected call of AddFriend.
func (mr *MockUserFriendRepoMockRecorder) AddFriend(ctx, userID, friendID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFriend", reflect.TypeOf((*MockUserFriendRepo)(nil).AddFriend), ctx, userID, friendID)
}

// DeleteFriend mocks base method.
func (m *MockUserFriendRepo) DeleteFriend(ctx context.Context, userID, friendID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFriend", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFriend indicates an expected call of DeleteFriend.
func (mr *MockUserFriendRepoMockRecorder) DeleteFriend(ctx, userID, friendID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFriend", reflect.TypeOf((*MockUserFriendRepo)(nil).DeleteFriend), ctx, userID, friendID)
}

// DeleteOutgoingFriendRequest mocks base method.
func (m *MockUserFriendRepo) DeleteOutgoingFriendRequest(ctx context.Context, requestID, fromUserID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOutgoingFriendRequest", ctx, requestID, fromUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOutgoingFriendRequest indicates an expected call of DeleteOutgoingFriendRequest.
func (mr *MockUserFriendRepoMockRecorder) DeleteOutgoingFriendRequest(ctx, requestID, fromUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOutgoingFriendRequest", reflect.TypeOf((*MockUserFriendRepo)(nil).DeleteOutgoingFriendRequest), ctx, requestID, fromUserID)
}

// GetFriendRequests mocks base method.
func (m *MockUserFriendRepo) GetFriendRequests(ctx context.Context, userID int64, direction string, limit int32) ([]domain.FriendRequestItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendRequests", ctx, userID, direction, limit)
	ret0, _ := ret[0].([]domain.FriendRequestItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendRequests indicates an expected call of GetFriendRequests.
func (mr *MockUserFriendRepoMockRecorder) GetFriendRequests(ctx, userID, direction, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendRequests", reflect.TypeOf((*MockUserFriendRepo)(nil).GetFriendRequests), ctx, userID, direction, limit)
}

// GetFriendsList mocks base method.
func (m *MockUserFriendRepo) GetFriendsList(ctx context.Context, userID int64, limit, offset int32) ([]domain.UserSearchResult, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendsList", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.UserSearchResult)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFriendsList indicates an expected call of GetFriendsList.
func (mr *MockUserFriendRepoMockRecorder) GetFriendsList(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendsList", reflect.TypeOf((*MockUserFriendRepo)(nil).GetFriendsList), ctx, userID, limit, offset)
}

// RespondToFriendRequest mocks base method.
func (m *MockUserFriendRepo) RespondToFriendRequest(ctx context.Context, requestID, userID int64, action string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondToFriendRequest", ctx, requestID, userID, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// RespondToFriendRequest indicates an expected call of RespondToFriendRequest.
func (mr *MockUserFriendRepoMockRecorder) RespondToFriendRequest(ctx, requestID, userID, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondToFriendRequest", reflect.TypeOf((*MockUserFriendRepo)(nil).RespondToFriendRequest), ctx, requestID, userID, action)
}

// SendFriendRequest mocks base method.
func (m *MockUserFriendRepo) SendFriendRequest(ctx context.Context, fromUserID, toUserID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFriendRequest", ctx, fromUserID, toUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFriendRequest indicates an expected call of SendFriendRequest.
func (mr *MockUserFriendRepoMockRecorder) SendFriendRequest(ctx, fromUserID, toUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFriendRequest", reflect.TypeOf((*MockUserFriendRepo)(nil).SendFriendRequest), ctx, fromUserID, toUserID)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// AddFriend mocks base method.
func (m *MockUserRepo) AddFriend(ctx context.Context, userID, friendID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFriend", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFriend indicates an expected call of AddFriend.
func (mr *MockUserRepoMockRecorder) AddFriend(ctx, userID, friendID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFriend", reflect.TypeOf((*MockUserRepo)(nil).AddFriend), ctx, userID, friendID)
}

// AddMovieToFavorites mocks base method.
func (m *MockUserRepo) AddMovieToFavorites(ctx context.Context, userID, movieID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMovieToFavorites", ctx, userID, movieID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMovieToFavorites indicates an expected call of AddMovieToFavorites.
func (mr *MockUserRepoMockRecorder) AddMovieToFavorites(ctx, userID, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMovieToFavorites", reflect.TypeOf((*MockUserRepo)(nil).AddMovieToFavorites), ctx, userID, movieID)
}

// CreateUserSubscription mocks base method.
func (m *MockUserRepo) CreateUserSubscription(ctx context.Context, userID, tariffID int64, startsAt, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserSubscription", ctx, userID, tariffID, startsAt, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserSubscription indicates an expected call of CreateUserSubscription.
func (mr *MockUserRepoMockRecorder) CreateUserSubscription(ctx, userID, tariffID, startsAt, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserSubscription", reflect.TypeOf((*MockUserRepo)(nil).CreateUserSubscription), ctx, userID, tariffID, startsAt, expiresAt)
}

// DeactivateUserSubscriptions mocks base method.
func (m *MockUserRepo) DeactivateUserSubscriptions(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUserSubscriptions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUserSubscriptions indicates an expected call of DeactivateUserSubscriptions.
func (mr *MockUserRepoMockRecorder) DeactivateUserSubscriptions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUserSubscriptions", reflect.TypeOf((*MockUserRepo)(nil).DeactivateUserSubscriptions), ctx, userID)
}

// DeleteFriend mocks base method.
func (m *MockUserRepo) DeleteFriend(ctx context.Context, userID, friendID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFriend", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFriend indicates an expected call of DeleteFriend.
func (mr *MockUserRepoMockRecorder) DeleteFriend(ctx, userID, friendID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFriend", reflect.TypeOf((*MockUserRepo)(nil).DeleteFriend), ctx, userID, friendID)
}

// DeleteMovieReview mocks base method.
func (m *MockUserRepo) DeleteMovieReview(ctx context.Context, userID, movieID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMovieReview", ctx, userID, movieID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMovieReview indicates an expected call of DeleteMovieReview.
func (mr *MockUserRepoMockRecorder) DeleteMovieReview(ctx, userID, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMovieReview", reflect.TypeOf((*MockUserRepo)(nil).DeleteMovieReview), ctx, userID, movieID)
}

// DeleteOutgoingFriendRequest mocks base method.
func (m *MockUserRepo) DeleteOutgoingFriendRequest(ctx context.Context, requestID, fromUserID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOutgoingFriendRequest", ctx, requestID, fromUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOutgoingFriendRequest indicates an expected call of DeleteOutgoingFriendRequest.
func (mr *MockUserRepoMockRecorder) DeleteOutgoingFriendRequest(ctx, requestID, fromUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOutgoingFriendRequest", reflect.TypeOf((*MockUserRepo)(nil).DeleteOutgoingFriendRequest), ctx, requestID, fromUserID)
}

// DeleteReviewReaction mocks base method.
func (m *MockUserRepo) DeleteReviewReaction(ctx context.Context, userID, reviewID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReviewReaction", ctx, userID, reviewID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReviewReaction indicates an expected call of DeleteReviewReaction.
func (mr *MockUserRepoMockRecorder) DeleteReviewReaction(ctx, userID, reviewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReviewReaction", reflect.TypeOf((*MockUserRepo)(nil).DeleteReviewReaction), ctx, userID, reviewID)
}

// GetActiveSubscription mocks base method.
func (m *MockUserRepo) GetActiveSubscription(ctx context.Context, userID int64) (domain.SubscriptionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSubscription", ctx, userID)
	ret0, _ := ret[0].(domain.SubscriptionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSubscription indicates an expected call of GetActiveSubscription.
func (mr *MockUserRepoMockRecorder) GetActiveSubscription(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSubscription", reflect.TypeOf((*MockUserRepo)(nil).GetActiveSubscription), ctx, userID)
}

// GetCoinsReceivedToday mocks base method.
func (m *MockUserRepo) GetCoinsReceivedToday(ctx context.Context, userID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinsReceivedToday", ctx, userID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinsReceivedToday indicates an expected call of GetCoinsReceivedToday.
func (mr *MockUserRepoMockRecorder) GetCoinsReceivedToday(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinsReceivedToday", reflect.TypeOf((*MockUserRepo)(nil).GetCoinsReceivedToday), ctx, userID)
}

// GetFavorites mocks base method.
func (m *MockUserRepo) GetFavorites(ctx context.Context, userID int64, limit, offset int32) ([]int64, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavorites", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFavorites indicates an expected call of GetFavorites.
func (mr *MockUserRepoMockRecorder) GetFavorites(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavorites", reflect.TypeOf((*MockUserRepo)(nil).GetFavorites), ctx, userID, limit, offset)
}

// GetFriend mocks base method.
func (m *MockUserRepo) GetFriend(ctx context.Context, userID, friendID int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriend", ctx, userID, friendID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriend indicates an expected call of GetFriend.
func (mr *MockUserRepoMockRecorder) GetFriend(ctx, userID, friendID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriend", reflect.TypeOf((*MockUserRepo)(nil).GetFriend), ctx, userID, friendID)
}

// GetFriendRequests mocks base method.
func (m *MockUserRepo) GetFriendRequests(ctx context.Context, userID int64, direction string, limit int32) ([]domain.FriendRequestItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendRequests", ctx, userID, direction, limit)
	ret0, _ := ret[0].([]domain.FriendRequestItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendRequests indicates an expected call of GetFriendRequests.
func (mr *MockUserRepoMockRecorder) GetFriendRequests(ctx, userID, direction, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendRequests", reflect.TypeOf((*MockUserRepo)(nil).GetFriendRequests), ctx, userID, direction, limit)
}

// GetFriendsList mocks base method.
func (m *MockUserRepo) GetFriendsList(ctx context.Context, userID int64, limit, offset int32) ([]domain.UserSearchResult, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendsList", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.UserSearchResult)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFriendsList indicates an expected call of GetFriendsList.
func (mr *MockUserRepoMockRecorder) GetFriendsList(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendsList", reflect.TypeOf((*MockUserRepo)(nil).GetFriendsList), ctx, userID, limit, offset)
}

// GetVKinoCoinsHistory mocks base method.
func (m *MockUserRepo) GetVKinoCoinsHistory(ctx context.Context, userID int64, limit, offset int32) ([]domain.VKinoCoinsHistoryItem, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVKinoCoinsHistory", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.VKinoCoinsHistoryItem)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVKinoCoinsHistory indicates an expected call of GetVKinoCoinsHistory.
func (mr *MockUserRepoMockRecorder) GetVKinoCoinsHistory(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVKinoCoinsHistory", reflect.TypeOf((*MockUserRepo)(nil).GetVKinoCoinsHistory), ctx, userID, limit, offset)
}

// GetRoomsCreatedThisMonth mocks base method.
func (m *MockUserRepo) GetRoomsCreatedThisMonth(ctx context.Context, userID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomsCreatedThisMonth", ctx, userID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomsCreatedThisMonth indicates an expected call of GetRoomsCreatedThisMonth.
func (mr *MockUserRepoMockRecorder) GetRoomsCreatedThisMonth(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomsCreatedThisMonth", reflect.TypeOf((*MockUserRepo)(nil).GetRoomsCreatedThisMonth), ctx, userID)
}

// GetSubscriptionTariffByCode mocks base method.
func (m *MockUserRepo) GetSubscriptionTariffByCode(ctx context.Context, code string) (domain.SubscriptionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionTariffByCode", ctx, code)
	ret0, _ := ret[0].(domain.SubscriptionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionTariffByCode indicates an expected call of GetSubscriptionTariffByCode.
func (mr *MockUserRepoMockRecorder) GetSubscriptionTariffByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionTariffByCode", reflect.TypeOf((*MockUserRepo)(nil).GetSubscriptionTariffByCode), ctx, code)
}

// GetSubscriptionTariffByID mocks base method.
func (m *MockUserRepo) GetSubscriptionTariffByID(ctx context.Context, tariffID int64) (domain.SubscriptionTariff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionTariffByID", ctx, tariffID)
	ret0, _ := ret[0].(domain.SubscriptionTariff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionTariffByID indicates an expected call of GetSubscriptionTariffByID.
func (mr *MockUserRepoMockRecorder) GetSubscriptionTariffByID(ctx, tariffID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionTariffByID", reflect.TypeOf((*MockUserRepo)(nil).GetSubscriptionTariffByID), ctx, tariffID)
}

// GetSubscriptionTariffOptions mocks base method.
func (m *MockUserRepo) GetSubscriptionTariffOptions(ctx context.Context, tariffID int64) ([]domain.SubscriptionOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionTariffOptions", ctx, tariffID)
	ret0, _ := ret[0].([]domain.SubscriptionOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionTariffOptions indicates an expected call of GetSubscriptionTariffOptions.
func (mr *MockUserRepoMockRecorder) GetSubscriptionTariffOptions(ctx, tariffID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionTariffOptions", reflect.TypeOf((*MockUserRepo)(nil).GetSubscriptionTariffOptions), ctx, tariffID)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepo) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepoMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserRepo) GetUserByID(ctx context.Context, id int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepoMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepo)(nil).GetUserByID), ctx, id)
}

// GetUserRole mocks base method.
func (m *MockUserRepo) GetUserRole(ctx context.Context, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockUserRepoMockRecorder) GetUserRole(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockUserRepo)(nil).GetUserRole), ctx, userID)
}

// RespondToFriendRequest mocks base method.
func (m *MockUserRepo) RespondToFriendRequest(ctx context.Context, requestID, userID int64, action string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondToFriendRequest", ctx, requestID, userID, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// RespondToFriendRequest indicates an expected call of RespondToFriendRequest.
func (mr *MockUserRepoMockRecorder) RespondToFriendRequest(ctx, requestID, userID, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondToFriendRequest", reflect.TypeOf((*MockUserRepo)(nil).RespondToFriendRequest), ctx, requestID, userID, action)
}

// SearchUsersByEmail mocks base method.
func (m *MockUserRepo) SearchUsersByEmail(ctx context.Context, userID int64, query string) ([]domain.UserSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersByEmail", ctx, userID, query)
	ret0, _ := ret[0].([]domain.UserSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersByEmail indicates an expected call of SearchUsersByEmail.
func (mr *MockUserRepoMockRecorder) SearchUsersByEmail(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersByEmail", reflect.TypeOf((*MockUserRepo)(nil).SearchUsersByEmail), ctx, userID, query)
}

// SendFriendRequest mocks base method.
func (m *MockUserRepo) SendFriendRequest(ctx context.Context, fromUserID, toUserID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFriendRequest", ctx, fromUserID, toUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFriendRequest indicates an expected call of SendFriendRequest.
func (mr *MockUserRepoMockRecorder) SendFriendRequest(ctx, fromUserID, toUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFriendRequest", reflect.TypeOf((*MockUserRepo)(nil).SendFriendRequest), ctx, fromUserID, toUserID)
}

// SetMovieRating mocks base method.
func (m *MockUserRepo) SetMovieRating(ctx context.Context, userID, movieID int64, rating float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMovieRating", ctx, userID, movieID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMovieRating indicates an expected call of SetMovieRating.
func (mr *MockUserRepoMockRecorder) SetMovieRating(ctx, userID, movieID, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMovieRating", reflect.TypeOf((*MockUserRepo)(nil).SetMovieRating), ctx, userID, movieID, rating)
}

// SetMovieReview mocks base method.
func (m *MockUserRepo) SetMovieReview(ctx context.Context, userID, movieID int64, rating *float64, comment *string) (domain.MovieReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMovieReview", ctx, userID, movieID, rating, comment)
	ret0, _ := ret[0].(domain.MovieReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMovieReview indicates an expected call of SetMovieReview.
func (mr *MockUserRepoMockRecorder) SetMovieReview(ctx, userID, movieID, rating, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMovieReview", reflect.TypeOf((*MockUserRepo)(nil).SetMovieReview), ctx, userID, movieID, rating, comment)
}

// SetReviewReaction mocks base method.
func (m *MockUserRepo) SetReviewReaction(ctx context.Context, userID, reviewID int64, reaction string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReviewReaction", ctx, userID, reviewID, reaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReviewReaction indicates an expected call of SetReviewReaction.
func (mr *MockUserRepoMockRecorder) SetReviewReaction(ctx, userID, reviewID, reaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReviewReaction", reflect.TypeOf((*MockUserRepo)(nil).SetReviewReaction), ctx, userID, reviewID, reaction)
}

// ToggleFavorite mocks base method.
func (m *MockUserRepo) ToggleFavorite(ctx context.Context, userID, movieID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleFavorite", ctx, userID, movieID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleFavorite indicates an expected call of ToggleFavorite.
func (mr *MockUserRepoMockRecorder) ToggleFavorite(ctx, userID, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleFavorite", reflect.TypeOf((*MockUserRepo)(nil).ToggleFavorite), ctx, userID, movieID)
}

// UpdateAvatarFileKey mocks base method.
func (m *MockUserRepo) UpdateAvatarFileKey(ctx context.Context, userID int64, avatarFileKey *string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatarFileKey", ctx, userID, avatarFileKey)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvatarFileKey indicates an expected call of UpdateAvatarFileKey.
func (mr *MockUserRepoMockRecorder) UpdateAvatarFileKey(ctx, userID, avatarFileKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatarFileKey", reflect.TypeOf((*MockUserRepo)(nil).UpdateAvatarFileKey), ctx, userID, avatarFileKey)
}

// UpdateBirthdate mocks base method.
func (m *MockUserRepo) UpdateBirthdate(ctx context.Context, userID int64, birthdate *time.Time) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBirthdate", ctx, userID, birthdate)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBirthdate indicates an expected call of UpdateBirthdate.
func (mr *MockUserRepoMockRecorder) UpdateBirthdate(ctx, userID, birthdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBirthdate", reflect.TypeOf((*MockUserRepo)(nil).UpdateBirthdate), ctx, userID, birthdate)
}

// MockSupportRepo is a mock of SupportRepo interface.
type MockSupportRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSupportRepoMockRecorder
	isgomock struct{}
}

// MockSupportRepoMockRecorder is the mock recorder for MockSupportRepo.
type MockSupportRepoMockRecorder struct {
	mock *MockSupportRepo
}

// NewMockSupportRepo creates a new mock instance.
func NewMockSupportRepo(ctrl *gomock.Controller) *MockSupportRepo {
	mock := &MockSupportRepo{ctrl: ctrl}
	mock.recorder = &MockSupportRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupportRepo) EXPECT() *MockSupportRepoMockRecorder {
	return m.recorder
}

// CreateTicket mocks base method.
func (m *MockSupportRepo) CreateTicket(ctx context.Context, userID int64, req domain.CreateSupportTicketRequest) (*domain.SupportTicketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicket", ctx, userID, req)
	ret0, _ := ret[0].(*domain.SupportTicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicket indicates an expected call of CreateTicket.
func (mr *MockSupportRepoMockRecorder) CreateTicket(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicket", reflect.TypeOf((*MockSupportRepo)(nil).CreateTicket), ctx, userID, req)
}

// CreateTicketMessage mocks base method.
func (m *MockSupportRepo) CreateTicketMessage(ctx context.Context, senderID int64, req domain.CreateSupportTicketMessageRequest) (*domain.SupportTicketMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicketMessage", ctx, senderID, req)
	ret0, _ := ret[0].(*domain.SupportTicketMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicketMessage indicates an expected call of CreateTicketMessage.
func (mr *MockSupportRepoMockRecorder) CreateTicketMessage(ctx, senderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicketMessage", reflect.TypeOf((*MockSupportRepo)(nil).CreateTicketMessage), ctx, senderID, req)
}

// GetTicketByID mocks base method.
func (m *MockSupportRepo) GetTicketByID(ctx context.Context, ticketID int64) (*domain.SupportTicketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketByID", ctx, ticketID)
	ret0, _ := ret[0].(*domain.SupportTicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketByID indicates an expected call of GetTicketByID.
func (mr *MockSupportRepoMockRecorder) GetTicketByID(ctx, ticketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketByID", reflect.TypeOf((*MockSupportRepo)(nil).GetTicketByID), ctx, ticketID)
}

// GetTicketMessages mocks base method.
func (m *MockSupportRepo) GetTicketMessages(ctx context.Context, ticketID int64) ([]domain.SupportTicketMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketMessages", ctx, ticketID)
	ret0, _ := ret[0].([]domain.SupportTicketMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketMessages indicates an expected call of GetTicketMessages.
func (mr *MockSupportRepoMockRecorder) GetTicketMessages(ctx, ticketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketMessages", reflect.TypeOf((*MockSupportRepo)(nil).GetTicketMessages), ctx, ticketID)
}

// GetTicketStatistics mocks base method.
func (m *MockSupportRepo) GetTicketStatistics(ctx context.Context, allowedCategories []string) (*domain.SupportTicketStatisticsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketStatistics", ctx, allowedCategories)
	ret0, _ := ret[0].(*domain.SupportTicketStatisticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketStatistics indicates an expected call of GetTicketStatistics.
func (mr *MockSupportRepoMockRecorder) GetTicketStatistics(ctx, allowedCategories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketStatistics", reflect.TypeOf((*MockSupportRepo)(nil).GetTicketStatistics), ctx, allowedCategories)
}

// GetTickets mocks base method.
func (m *MockSupportRepo) GetTickets(ctx context.Context, userID int64, req domain.GetSupportTicketsRequest) ([]domain.SupportTicketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTickets", ctx, userID, req)
	ret0, _ := ret[0].([]domain.SupportTicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickets indicates an expected call of GetTickets.
func (mr *MockSupportRepoMockRecorder) GetTickets(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickets", reflect.TypeOf((*MockSupportRepo)(nil).GetTickets), ctx, userID, req)
}

// HasTicketFile mocks base method.
func (m *MockSupportRepo) HasTicketFile(ctx context.Context, ticketID int64, fileKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTicketFile", ctx, ticketID, fileKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasTicketFile indicates an expected call of HasTicketFile.
func (mr *MockSupportRepoMockRecorder) HasTicketFile(ctx, ticketID, fileKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTicketFile", reflect.TypeOf((*MockSupportRepo)(nil).HasTicketFile), ctx, ticketID, fileKey)
}

// UpdateTicket mocks base method.
func (m *MockSupportRepo) UpdateTicket(ctx context.Context, req domain.UpdateSupportTicketRequest) (*domain.SupportTicketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTicket", ctx, req)
	ret0, _ := ret[0].(*domain.SupportTicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTicket indicates an expected call of UpdateTicket.
func (mr *MockSupportRepoMockRecorder) UpdateTicket(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTicket", reflect.TypeOf((*MockSupportRepo)(nil).UpdateTicket), ctx, req)
}
