// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination=./mocks/user_repo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/go-park-mail-ru/2026_1_VKino/internal/app/user-service/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// AddFriend mocks base method.
func (m *MockUserRepo) AddFriend(ctx context.Context, userID, friendID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFriend", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFriend indicates an expected call of AddFriend.
func (mr *MockUserRepoMockRecorder) AddFriend(ctx, userID, friendID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFriend", reflect.TypeOf((*MockUserRepo)(nil).AddFriend), ctx, userID, friendID)
}

// AddMovieToFavorites mocks base method.
func (m *MockUserRepo) AddMovieToFavorites(ctx context.Context, userID, movieID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMovieToFavorites", ctx, userID, movieID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMovieToFavorites indicates an expected call of AddMovieToFavorites.
func (mr *MockUserRepoMockRecorder) AddMovieToFavorites(ctx, userID, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMovieToFavorites", reflect.TypeOf((*MockUserRepo)(nil).AddMovieToFavorites), ctx, userID, movieID)
}

// DeleteFriend mocks base method.
func (m *MockUserRepo) DeleteFriend(ctx context.Context, userID, friendID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFriend", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFriend indicates an expected call of DeleteFriend.
func (mr *MockUserRepoMockRecorder) DeleteFriend(ctx, userID, friendID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFriend", reflect.TypeOf((*MockUserRepo)(nil).DeleteFriend), ctx, userID, friendID)
}

// DeleteOutgoingFriendRequest mocks base method.
func (m *MockUserRepo) DeleteOutgoingFriendRequest(ctx context.Context, requestID, fromUserID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOutgoingFriendRequest", ctx, requestID, fromUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOutgoingFriendRequest indicates an expected call of DeleteOutgoingFriendRequest.
func (mr *MockUserRepoMockRecorder) DeleteOutgoingFriendRequest(ctx, requestID, fromUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOutgoingFriendRequest", reflect.TypeOf((*MockUserRepo)(nil).DeleteOutgoingFriendRequest), ctx, requestID, fromUserID)
}

// GetFavorites mocks base method.
func (m *MockUserRepo) GetFavorites(ctx context.Context, userID int64, limit, offset int32) ([]int64, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavorites", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFavorites indicates an expected call of GetFavorites.
func (mr *MockUserRepoMockRecorder) GetFavorites(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavorites", reflect.TypeOf((*MockUserRepo)(nil).GetFavorites), ctx, userID, limit, offset)
}

// GetFriendRequests mocks base method.
func (m *MockUserRepo) GetFriendRequests(ctx context.Context, userID int64, direction string, limit int32) ([]domain.FriendRequestItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendRequests", ctx, userID, direction, limit)
	ret0, _ := ret[0].([]domain.FriendRequestItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendRequests indicates an expected call of GetFriendRequests.
func (mr *MockUserRepoMockRecorder) GetFriendRequests(ctx, userID, direction, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendRequests", reflect.TypeOf((*MockUserRepo)(nil).GetFriendRequests), ctx, userID, direction, limit)
}

// GetFriendsList mocks base method.
func (m *MockUserRepo) GetFriendsList(ctx context.Context, userID int64, limit, offset int32) ([]domain.UserSearchResult, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendsList", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.UserSearchResult)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFriendsList indicates an expected call of GetFriendsList.
func (mr *MockUserRepoMockRecorder) GetFriendsList(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendsList", reflect.TypeOf((*MockUserRepo)(nil).GetFriendsList), ctx, userID, limit, offset)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepo) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepoMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserRepo) GetUserByID(ctx context.Context, id int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepoMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepo)(nil).GetUserByID), ctx, id)
}

// GetUserRole mocks base method.
func (m *MockUserRepo) GetUserRole(ctx context.Context, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockUserRepoMockRecorder) GetUserRole(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockUserRepo)(nil).GetUserRole), ctx, userID)
}

// RespondToFriendRequest mocks base method.
func (m *MockUserRepo) RespondToFriendRequest(ctx context.Context, requestID, userID int64, action string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondToFriendRequest", ctx, requestID, userID, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// RespondToFriendRequest indicates an expected call of RespondToFriendRequest.
func (mr *MockUserRepoMockRecorder) RespondToFriendRequest(ctx, requestID, userID, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondToFriendRequest", reflect.TypeOf((*MockUserRepo)(nil).RespondToFriendRequest), ctx, requestID, userID, action)
}

// SearchUsersByEmail mocks base method.
func (m *MockUserRepo) SearchUsersByEmail(ctx context.Context, userID int64, query string) ([]domain.UserSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersByEmail", ctx, userID, query)
	ret0, _ := ret[0].([]domain.UserSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersByEmail indicates an expected call of SearchUsersByEmail.
func (mr *MockUserRepoMockRecorder) SearchUsersByEmail(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersByEmail", reflect.TypeOf((*MockUserRepo)(nil).SearchUsersByEmail), ctx, userID, query)
}

// SendFriendRequest mocks base method.
func (m *MockUserRepo) SendFriendRequest(ctx context.Context, fromUserID, toUserID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFriendRequest", ctx, fromUserID, toUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFriendRequest indicates an expected call of SendFriendRequest.
func (mr *MockUserRepoMockRecorder) SendFriendRequest(ctx, fromUserID, toUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFriendRequest", reflect.TypeOf((*MockUserRepo)(nil).SendFriendRequest), ctx, fromUserID, toUserID)
}

// ToggleFavorite mocks base method.
func (m *MockUserRepo) ToggleFavorite(ctx context.Context, userID, movieID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleFavorite", ctx, userID, movieID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleFavorite indicates an expected call of ToggleFavorite.
func (mr *MockUserRepoMockRecorder) ToggleFavorite(ctx, userID, movieID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleFavorite", reflect.TypeOf((*MockUserRepo)(nil).ToggleFavorite), ctx, userID, movieID)
}

// UpdateAvatarFileKey mocks base method.
func (m *MockUserRepo) UpdateAvatarFileKey(ctx context.Context, userID int64, avatarFileKey *string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatarFileKey", ctx, userID, avatarFileKey)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvatarFileKey indicates an expected call of UpdateAvatarFileKey.
func (mr *MockUserRepoMockRecorder) UpdateAvatarFileKey(ctx, userID, avatarFileKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatarFileKey", reflect.TypeOf((*MockUserRepo)(nil).UpdateAvatarFileKey), ctx, userID, avatarFileKey)
}

// UpdateBirthdate mocks base method.
func (m *MockUserRepo) UpdateBirthdate(ctx context.Context, userID int64, birthdate *time.Time) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBirthdate", ctx, userID, birthdate)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBirthdate indicates an expected call of UpdateBirthdate.
func (mr *MockUserRepoMockRecorder) UpdateBirthdate(ctx, userID, birthdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBirthdate", reflect.TypeOf((*MockUserRepo)(nil).UpdateBirthdate), ctx, userID, birthdate)
}

// MockSupportRepo is a mock of SupportRepo interface.
type MockSupportRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSupportRepoMockRecorder
	isgomock struct{}
}

// MockSupportRepoMockRecorder is the mock recorder for MockSupportRepo.
type MockSupportRepoMockRecorder struct {
	mock *MockSupportRepo
}

// NewMockSupportRepo creates a new mock instance.
func NewMockSupportRepo(ctrl *gomock.Controller) *MockSupportRepo {
	mock := &MockSupportRepo{ctrl: ctrl}
	mock.recorder = &MockSupportRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupportRepo) EXPECT() *MockSupportRepoMockRecorder {
	return m.recorder
}

// CreateTicket mocks base method.
func (m *MockSupportRepo) CreateTicket(ctx context.Context, userID int64, req domain.CreateSupportTicketRequest) (*domain.SupportTicketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicket", ctx, userID, req)
	ret0, _ := ret[0].(*domain.SupportTicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicket indicates an expected call of CreateTicket.
func (mr *MockSupportRepoMockRecorder) CreateTicket(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicket", reflect.TypeOf((*MockSupportRepo)(nil).CreateTicket), ctx, userID, req)
}

// CreateTicketMessage mocks base method.
func (m *MockSupportRepo) CreateTicketMessage(ctx context.Context, senderID int64, req domain.CreateSupportTicketMessageRequest) (*domain.SupportTicketMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicketMessage", ctx, senderID, req)
	ret0, _ := ret[0].(*domain.SupportTicketMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicketMessage indicates an expected call of CreateTicketMessage.
func (mr *MockSupportRepoMockRecorder) CreateTicketMessage(ctx, senderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicketMessage", reflect.TypeOf((*MockSupportRepo)(nil).CreateTicketMessage), ctx, senderID, req)
}

// GetTicketByID mocks base method.
func (m *MockSupportRepo) GetTicketByID(ctx context.Context, ticketID int64) (*domain.SupportTicketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketByID", ctx, ticketID)
	ret0, _ := ret[0].(*domain.SupportTicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketByID indicates an expected call of GetTicketByID.
func (mr *MockSupportRepoMockRecorder) GetTicketByID(ctx, ticketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketByID", reflect.TypeOf((*MockSupportRepo)(nil).GetTicketByID), ctx, ticketID)
}

// GetTicketMessages mocks base method.
func (m *MockSupportRepo) GetTicketMessages(ctx context.Context, ticketID int64) ([]domain.SupportTicketMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketMessages", ctx, ticketID)
	ret0, _ := ret[0].([]domain.SupportTicketMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketMessages indicates an expected call of GetTicketMessages.
func (mr *MockSupportRepoMockRecorder) GetTicketMessages(ctx, ticketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketMessages", reflect.TypeOf((*MockSupportRepo)(nil).GetTicketMessages), ctx, ticketID)
}

// GetTicketStatistics mocks base method.
func (m *MockSupportRepo) GetTicketStatistics(ctx context.Context) (*domain.SupportTicketStatisticsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketStatistics", ctx)
	ret0, _ := ret[0].(*domain.SupportTicketStatisticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketStatistics indicates an expected call of GetTicketStatistics.
func (mr *MockSupportRepoMockRecorder) GetTicketStatistics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketStatistics", reflect.TypeOf((*MockSupportRepo)(nil).GetTicketStatistics), ctx)
}

// GetTickets mocks base method.
func (m *MockSupportRepo) GetTickets(ctx context.Context, userID int64, req domain.GetSupportTicketsRequest) ([]domain.SupportTicketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTickets", ctx, userID, req)
	ret0, _ := ret[0].([]domain.SupportTicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickets indicates an expected call of GetTickets.
func (mr *MockSupportRepoMockRecorder) GetTickets(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickets", reflect.TypeOf((*MockSupportRepo)(nil).GetTickets), ctx, userID, req)
}

// UpdateTicket mocks base method.
func (m *MockSupportRepo) UpdateTicket(ctx context.Context, req domain.UpdateSupportTicketRequest) (*domain.SupportTicketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTicket", ctx, req)
	ret0, _ := ret[0].(*domain.SupportTicketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTicket indicates an expected call of UpdateTicket.
func (mr *MockSupportRepoMockRecorder) UpdateTicket(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTicket", reflect.TypeOf((*MockSupportRepo)(nil).UpdateTicket), ctx, req)
}
