services:
  nginx:
    image: nginx:latest
    container_name: front-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend-dist:/usr/share/nginx/html:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - app-network 

  vkinoapi:
    image: alethandrina/vkino-back:v0.1.8
    platform: linux/amd64
    restart: always
    command: ./vkinoapi --config=/usr/local/etc/config.yaml
    volumes:
      - ./vkinoapi/config.yaml:/usr/local/etc/config.yaml
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    networks:
      - app-network  

  db:
    image: postgres:18.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - app-network 

  migrate:
    image: migrate/migrate
    volumes:
      - ../../migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - app-network 


  minio:
    image: minio/minio:latest
    container_name: vkino-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: http://minio.vkino.tech
      MINIO_SERVER_URL: http://media.vkino.tech
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin; do
        echo 'waiting for minio...';
        sleep 2;
      done;
      /usr/bin/mc mb -p local/vkino-images || true;
      /usr/bin/mc mb -p local/vkino-avatars || true;
      /usr/bin/mc mb -p local/vkino-videos || true;
      /usr/bin/mc anonymous set none local/vkino-images || true;
      /usr/bin/mc anonymous set none local/vkino-avatars || true;
      /usr/bin/mc anonymous set none local/vkino-videos || true;
      exit 0;
      "
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - app-network

networks:
  app-network:  

volumes:
  db-data:
  minio_data: