services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
  vkinoapi:
    image: vkino-back:latest
    container_name: vkino-api
    restart: always
    ports:
      - 8080

